// Compatibility Quiz question bank — unlike "What Would You Say?" (one of you
// self-reports, the other predicts), this is a simultaneous "are we in sync"
// quiz: both of you answer the SAME question about "us" at the same time,
// and score a point each when your answers match. Two shapes:
//  - type "who": a fixed options list of who-does-this-more.
//  - type "pick": a bespoke options list of concrete choices.
const WHO_OPTIONS = ['Louie', 'Ariel', 'Both of us equally', 'Neither of us'];

const QUESTIONS = [
  { id: 'c001', type: 'who', question: "Who's the messier one?", options: WHO_OPTIONS },
  { id: 'c002', type: 'who', question: 'Who takes longer to get ready?', options: WHO_OPTIONS },
  { id: 'c003', type: 'who', question: 'Who falls asleep first during a movie?', options: WHO_OPTIONS },
  { id: 'c004', type: 'who', question: "Who's the better cook?", options: WHO_OPTIONS },
  { id: 'c005', type: 'who', question: 'Who checks their phone more?', options: WHO_OPTIONS },
  { id: 'c006', type: 'who', question: 'Who is more likely to cry at a film?', options: WHO_OPTIONS },
  { id: 'c007', type: 'who', question: 'Who is the better driver?', options: WHO_OPTIONS },
  { id: 'c008', type: 'who', question: 'Who holds a grudge longer?', options: WHO_OPTIONS },
  { id: 'c009', type: 'who', question: "Who's more likely to forget an umbrella?", options: WHO_OPTIONS },
  { id: 'c010', type: 'who', question: 'Who is the bigger cheapskate?', options: WHO_OPTIONS },
  { id: 'c011', type: 'who', question: 'Who is louder when singing in the car?', options: WHO_OPTIONS },
  { id: 'c012', type: 'who', question: 'Who snores more?', options: WHO_OPTIONS },
  { id: 'c013', type: 'who', question: 'Who is more competitive at board games?', options: WHO_OPTIONS },
  { id: 'c014', type: 'who', question: 'Who takes up more of the bed?', options: WHO_OPTIONS },
  { id: 'c015', type: 'who', question: 'Who is more likely to plan a surprise?', options: WHO_OPTIONS },
  { id: 'c016', type: 'who', question: 'Who is more stubborn?', options: WHO_OPTIONS },
  { id: 'c017', type: 'who', question: "Who's more likely to double text?", options: WHO_OPTIONS },
  { id: 'c018', type: 'who', question: 'Who is the better dancer?', options: WHO_OPTIONS },
  { id: 'c019', type: 'who', question: 'Who is more likely to hit snooze five times?', options: WHO_OPTIONS },
  { id: 'c020', type: 'who', question: 'Who talks in their sleep?', options: WHO_OPTIONS },
  { id: 'c021', type: 'who', question: 'Who is more likely to lose their keys?', options: WHO_OPTIONS },
  { id: 'c022', type: 'who', question: "Who's the bigger foodie?", options: WHO_OPTIONS },
  { id: 'c023', type: 'who', question: 'Who apologises first after an argument?', options: WHO_OPTIONS },
  { id: 'c024', type: 'who', question: 'Who is more likely to cancel plans last minute?', options: WHO_OPTIONS },
  { id: 'c025', type: 'who', question: 'Who is the better gift-giver?', options: WHO_OPTIONS },
  { id: 'c026', type: 'who', question: 'Who spends longer choosing what to watch?', options: WHO_OPTIONS },
  { id: 'c027', type: 'who', question: 'Who is more likely to burn dinner?', options: WHO_OPTIONS },
  { id: 'c028', type: 'who', question: 'Who is the early bird?', options: WHO_OPTIONS },
  { id: 'c029', type: 'who', question: "Who's more likely to cry happy tears?", options: WHO_OPTIONS },
  { id: 'c030', type: 'who', question: 'Who complains more about the cold?', options: WHO_OPTIONS },
  {
    id: 'c031',
    type: 'pick',
    question: "What's our go-to Friday night?",
    options: ['Takeaway + movie', 'Pub with mates', 'Cooking together', 'Early night'],
  },
  {
    id: 'c032',
    type: 'pick',
    question: 'Beach holiday or city break?',
    options: ['Beach holiday', 'City break', 'Mountains/hiking', 'Staycation'],
  },
  {
    id: 'c033',
    type: 'pick',
    question: "What's our go-to comfort food?",
    options: ['Pizza', 'Chinese takeaway', 'Pasta', 'A cheeky Nando\'s'],
  },
  {
    id: 'c034',
    type: 'pick',
    question: 'Ideal weekend morning?',
    options: ['Lie-in + brunch', 'Early walk/run', 'Sleep till noon', 'Up early doing chores'],
  },
  {
    id: 'c035',
    type: 'pick',
    question: "What's playing at our wedding first dance?",
    options: ['A slow romantic ballad', 'Something we both know all the words to', 'A cheesy 2000s pop song', 'Whatever the DJ picks'],
  },
  {
    id: 'c036',
    type: 'pick',
    question: 'Dream pet (if we got one tomorrow)?',
    options: ['Dog', 'Cat', 'Something exotic', 'No pets, thanks'],
  },
  {
    id: 'c037',
    type: 'pick',
    question: 'Go-to date night activity?',
    options: ['Dinner out', 'Cinema', 'Cosy night in', 'Something active/new'],
  },
  {
    id: 'c038',
    type: 'pick',
    question: 'What ends most of our arguments?',
    options: ['One of us laughs first', 'A hug', 'Just changing the subject', 'Food'],
  },
  {
    id: 'c039',
    type: 'pick',
    question: 'Favourite way to spend a rainy day together?',
    options: ['Movie marathon', 'Board games', 'Baking/cooking', 'Napping'],
  },
  {
    id: 'c040',
    type: 'pick',
    question: 'If we won the lottery tomorrow, first thing we\'d do?',
    options: ['Book a big holiday', 'Pay off everything sensible', 'Buy a house', 'Treat ourselves silly for a day'],
  },
  {
    id: 'c041',
    type: 'pick',
    question: 'Our go-to takeaway order?',
    options: ['Chinese', 'Indian', 'Pizza', 'Thai'],
  },
  {
    id: 'c042',
    type: 'pick',
    question: 'Which of these describes us best as a couple?',
    options: ['Chaotic but loving', 'Calm and steady', 'Bicker but never bored', 'Attached at the hip'],
  },
  {
    id: 'c043',
    type: 'pick',
    question: "What's the most 'us' way to spend our anniversary?",
    options: ['A fancy dinner out', 'Recreating our first date', 'A weekend away', 'Staying in, just us'],
  },
  {
    id: 'c044',
    type: 'pick',
    question: 'Which pet name gets used the most?',
    options: ['Babe', 'Love', 'A silly nickname', 'First names only'],
  },
  {
    id: 'c045',
    type: 'pick',
    question: 'Our ideal Sunday?',
    options: ['Big roast dinner', 'Long walk together', 'Doing nothing at all', 'Catching up on errands'],
  },
  {
    id: 'c046',
    type: 'pick',
    question: 'What genre do we always end up watching?',
    options: ['Comedy', 'True crime', 'Rom-com', 'Action/thriller'],
  },
  {
    id: 'c047',
    type: 'pick',
    question: 'Which of us picked where we live?',
    options: ['Louie mostly', 'Ariel mostly', 'Totally mutual', 'It just happened'],
  },
  {
    id: 'c048',
    type: 'pick',
    question: 'Biggest source of our playful arguments?',
    options: ['Who does more chores', 'Thermostat wars', 'What to watch', 'Directions/navigating'],
  },
  {
    id: 'c049',
    type: 'pick',
    question: 'What would our couple Halloween costume be?',
    options: ['Matching cute duo', 'Something funny/punny', 'Horror movie characters', 'We\'d never agree on one'],
  },
  {
    id: 'c050',
    type: 'pick',
    question: 'Our go-to celebration when something good happens?',
    options: ['Order a takeaway', 'Go out for drinks', 'A nice dinner out', 'Just a big hug and telling everyone'],
  },
];

module.exports = { QUESTIONS };
