// Doodle Duel word bank — drawable prompts across a few categories, mostly
// generic (so any two players could use them) with a handful of "us" words
// mixed in for a personal touch. `difficulty` isn't surfaced in the UI yet,
// it's just there so a difficulty picker can be added later without a data
// migration.
const CATEGORIES = {
  animals: { label: '🐾 Animals' },
  food: { label: '🍕 Food' },
  objects: { label: '📦 Objects' },
  actions: { label: '🏃 Actions' },
  places: { label: '🌍 Places' },
  nature: { label: '🌳 Nature' },
  us: { label: '💕 Us' },
};

const WORDS = [
  // Animals
  { word: 'Elephant', category: 'animals', difficulty: 'easy' },
  { word: 'Cat', category: 'animals', difficulty: 'easy' },
  { word: 'Dog', category: 'animals', difficulty: 'easy' },
  { word: 'Fish', category: 'animals', difficulty: 'easy' },
  { word: 'Snake', category: 'animals', difficulty: 'easy' },
  { word: 'Spider', category: 'animals', difficulty: 'easy' },
  { word: 'Butterfly', category: 'animals', difficulty: 'medium' },
  { word: 'Octopus', category: 'animals', difficulty: 'medium' },
  { word: 'Kangaroo', category: 'animals', difficulty: 'medium' },
  { word: 'Penguin', category: 'animals', difficulty: 'easy' },
  { word: 'Giraffe', category: 'animals', difficulty: 'medium' },
  { word: 'Flamingo', category: 'animals', difficulty: 'medium' },
  { word: 'Dinosaur', category: 'animals', difficulty: 'medium' },
  { word: 'Owl', category: 'animals', difficulty: 'easy' },
  { word: 'Crab', category: 'animals', difficulty: 'easy' },
  { word: 'Snail', category: 'animals', difficulty: 'easy' },
  { word: 'Bee', category: 'animals', difficulty: 'easy' },
  { word: 'Shark', category: 'animals', difficulty: 'easy' },
  { word: 'Bat', category: 'animals', difficulty: 'medium' },
  { word: 'Peacock', category: 'animals', difficulty: 'hard' },

  // Food
  { word: 'Pizza', category: 'food', difficulty: 'easy' },
  { word: 'Ice Cream', category: 'food', difficulty: 'easy' },
  { word: 'Sushi', category: 'food', difficulty: 'medium' },
  { word: 'Birthday Cake', category: 'food', difficulty: 'medium' },
  { word: 'Taco', category: 'food', difficulty: 'easy' },
  { word: 'Popcorn', category: 'food', difficulty: 'medium' },
  { word: 'Watermelon', category: 'food', difficulty: 'easy' },
  { word: 'Donut', category: 'food', difficulty: 'easy' },
  { word: 'Hot Dog', category: 'food', difficulty: 'easy' },
  { word: 'Pancakes', category: 'food', difficulty: 'medium' },
  { word: 'Sandwich', category: 'food', difficulty: 'easy' },
  { word: 'Croissant', category: 'food', difficulty: 'medium' },
  { word: 'Coffee Cup', category: 'food', difficulty: 'easy' },
  { word: 'Egg', category: 'food', difficulty: 'easy' },
  { word: 'Cheese', category: 'food', difficulty: 'medium' },
  { word: 'Noodles', category: 'food', difficulty: 'medium' },
  { word: 'Cupcake', category: 'food', difficulty: 'easy' },
  { word: 'Wine Glass', category: 'food', difficulty: 'medium' },

  // Objects
  { word: 'Umbrella', category: 'objects', difficulty: 'easy' },
  { word: 'Guitar', category: 'objects', difficulty: 'medium' },
  { word: 'Clock', category: 'objects', difficulty: 'easy' },
  { word: 'Camera', category: 'objects', difficulty: 'medium' },
  { word: 'Rocket', category: 'objects', difficulty: 'medium' },
  { word: 'Balloon', category: 'objects', difficulty: 'easy' },
  { word: 'Key', category: 'objects', difficulty: 'easy' },
  { word: 'Lamp', category: 'objects', difficulty: 'easy' },
  { word: 'Glasses', category: 'objects', difficulty: 'easy' },
  { word: 'Backpack', category: 'objects', difficulty: 'medium' },
  { word: 'Crown', category: 'objects', difficulty: 'easy' },
  { word: 'Suitcase', category: 'objects', difficulty: 'medium' },
  { word: 'Telephone', category: 'objects', difficulty: 'medium' },
  { word: 'Anchor', category: 'objects', difficulty: 'medium' },
  { word: 'Robot', category: 'objects', difficulty: 'medium' },
  { word: 'Ladder', category: 'objects', difficulty: 'easy' },
  { word: 'Candle', category: 'objects', difficulty: 'easy' },
  { word: 'Kite', category: 'objects', difficulty: 'easy' },
  { word: 'Piano', category: 'objects', difficulty: 'medium' },
  { word: 'Bicycle', category: 'objects', difficulty: 'medium' },
  { word: 'Sunglasses', category: 'objects', difficulty: 'easy' },
  { word: 'Treasure Chest', category: 'objects', difficulty: 'hard' },
  { word: 'Hourglass', category: 'objects', difficulty: 'hard' },

  // Actions
  { word: 'Dancing', category: 'actions', difficulty: 'medium' },
  { word: 'Sleeping', category: 'actions', difficulty: 'easy' },
  { word: 'Swimming', category: 'actions', difficulty: 'medium' },
  { word: 'Laughing', category: 'actions', difficulty: 'medium' },
  { word: 'Running', category: 'actions', difficulty: 'easy' },
  { word: 'Singing', category: 'actions', difficulty: 'medium' },
  { word: 'Crying', category: 'actions', difficulty: 'medium' },
  { word: 'Fishing', category: 'actions', difficulty: 'medium' },
  { word: 'Skiing', category: 'actions', difficulty: 'medium' },
  { word: 'Juggling', category: 'actions', difficulty: 'hard' },
  { word: 'Yoga', category: 'actions', difficulty: 'medium' },
  { word: 'Climbing', category: 'actions', difficulty: 'medium' },
  { word: 'Snoring', category: 'actions', difficulty: 'hard' },

  // Places
  { word: 'Beach', category: 'places', difficulty: 'easy' },
  { word: 'Castle', category: 'places', difficulty: 'medium' },
  { word: 'Volcano', category: 'places', difficulty: 'medium' },
  { word: 'Desert Island', category: 'places', difficulty: 'medium' },
  { word: 'Airport', category: 'places', difficulty: 'medium' },
  { word: 'Farm', category: 'places', difficulty: 'medium' },
  { word: 'Space Station', category: 'places', difficulty: 'hard' },
  { word: 'Lighthouse', category: 'places', difficulty: 'medium' },
  { word: 'Waterfall', category: 'places', difficulty: 'medium' },
  { word: 'City Skyline', category: 'places', difficulty: 'hard' },
  { word: 'Igloo', category: 'places', difficulty: 'easy' },
  { word: 'Bridge', category: 'places', difficulty: 'easy' },
  { word: 'Mountain', category: 'places', difficulty: 'easy' },

  // Nature
  { word: 'Rainbow', category: 'nature', difficulty: 'easy' },
  { word: 'Sunset', category: 'nature', difficulty: 'medium' },
  { word: 'Tornado', category: 'nature', difficulty: 'medium' },
  { word: 'Snowman', category: 'nature', difficulty: 'easy' },
  { word: 'Palm Tree', category: 'nature', difficulty: 'easy' },
  { word: 'Lightning', category: 'nature', difficulty: 'medium' },
  { word: 'Cactus', category: 'nature', difficulty: 'easy' },
  { word: 'Sunflower', category: 'nature', difficulty: 'medium' },
  { word: 'Cloud', category: 'nature', difficulty: 'easy' },
  { word: 'Campfire', category: 'nature', difficulty: 'medium' },
  { word: 'Moon', category: 'nature', difficulty: 'easy' },
  { word: 'Star', category: 'nature', difficulty: 'easy' },

  // Us — a personal touch, pulled loosely from things around this app
  { word: 'Hugo Spritz', category: 'us', difficulty: 'medium' },
  { word: 'Green M&M', category: 'us', difficulty: 'medium' },
  { word: 'Date Night', category: 'us', difficulty: 'hard' },
  { word: 'The Puppy', category: 'us', difficulty: 'easy' },
  { word: 'Pizza Night', category: 'us', difficulty: 'medium' },
  { word: 'Road Trip', category: 'us', difficulty: 'medium' },
  { word: 'Movie Night', category: 'us', difficulty: 'medium' },
  { word: 'Engagement Ring', category: 'us', difficulty: 'medium' },
  { word: 'Wedding Cake', category: 'us', difficulty: 'medium' },
  { word: 'Honeymoon', category: 'us', difficulty: 'hard' },
  { word: 'Cuddling', category: 'us', difficulty: 'medium' },
  { word: 'First Kiss', category: 'us', difficulty: 'hard' },
];

const DECK = WORDS.map((w, i) => ({ id: i, ...w }));

module.exports = { DECK, CATEGORIES };
