// Emoji Decode puzzle bank — same racing/buzzer engine as Trivia Showdown
// (see server.js triviaRooms), just with an emoji string as the "question"
// instead of text, and multiple-choice answers to keep scoring unambiguous.
const EMOJI_PUZZLES = [
  { id: 'e001', category: 'movie', emoji: '🦁👑', options: ['The Lion King', 'Madagascar', 'Zootopia', 'The Jungle Book'], correctIndex: 0 },
  { id: 'e002', category: 'movie', emoji: '🕷️🧑', options: ['Spider-Man', 'Ant-Man', 'Venom', 'X-Men'], correctIndex: 0 },
  { id: 'e003', category: 'movie', emoji: '🚢🧊💔', options: ['Titanic', 'Frozen', 'The Perfect Storm', 'Life of Pi'], correctIndex: 0 },
  { id: 'e004', category: 'movie', emoji: '🧙‍♂️💍🌋', options: ['The Lord of the Rings', 'Harry Potter', 'Shrek', 'Narnia'], correctIndex: 0 },
  { id: 'e005', category: 'movie', emoji: '🦈🌊', options: ['Jaws', 'Finding Nemo', 'Moana', 'The Meg'], correctIndex: 0 },
  { id: 'e006', category: 'movie', emoji: '👻🚫', options: ['Ghostbusters', 'Casper', 'Poltergeist', 'The Conjuring'], correctIndex: 0 },
  { id: 'e007', category: 'movie', emoji: '🧊👸❄️', options: ['Frozen', 'Ice Age', 'The Snow Queen', 'Happy Feet'], correctIndex: 0 },
  { id: 'e008', category: 'movie', emoji: '🍫🏭', options: ['Charlie and the Chocolate Factory', 'Wreck-It Ralph', 'Chicken Run', 'Paddington'], correctIndex: 0 },
  { id: 'e009', category: 'movie', emoji: '🦖🏝️', options: ['Jurassic Park', 'King Kong', 'Godzilla', 'The Land Before Time'], correctIndex: 0 },
  { id: 'e010', category: 'movie', emoji: '🐟🔍', options: ['Finding Nemo', 'The Little Mermaid', 'Shark Tale', 'Moana'], correctIndex: 0 },
  { id: 'e011', category: 'movie', emoji: '🤖❤️🌍', options: ['WALL-E', 'Transformers', 'Big Hero 6', 'I, Robot'], correctIndex: 0 },
  { id: 'e012', category: 'movie', emoji: '👗🕛👠', options: ['Cinderella', 'Sleeping Beauty', 'Pretty Woman', 'The Devil Wears Prada'], correctIndex: 0 },
  { id: 'e013', category: 'movie', emoji: '🦇🌃', options: ['Batman', 'Superman', 'Daredevil', 'The Crow'], correctIndex: 0 },
  { id: 'e014', category: 'movie', emoji: '👦🪄⚡', options: ['Harry Potter', 'Percy Jackson', 'The Wizard of Oz', 'Merlin'], correctIndex: 0 },
  { id: 'e015', category: 'movie', emoji: '🐜🌎', options: ["A Bug's Life", 'Antz', 'Ratatouille', 'Bee Movie'], correctIndex: 0 },
  { id: 'e016', category: 'movie', emoji: '👑🦁🌅', options: ['The Lion King', 'Madagascar', 'Kung Fu Panda', 'Rio'], correctIndex: 0 },
  { id: 'e017', category: 'movie', emoji: '🎈🏠👴', options: ['Up', 'The Wizard of Oz', 'Cloudy with a Chance of Meatballs', 'Coco'], correctIndex: 0 },
  { id: 'e018', category: 'movie', emoji: '🐠🌊👑', options: ['Finding Nemo', 'The Little Mermaid', 'Moana', 'SpongeBob'], correctIndex: 1 },
  { id: 'e019', category: 'movie', emoji: '🚗⚡🏁', options: ['Cars', 'Fast & Furious', 'Speed Racer', 'Grease'], correctIndex: 0 },
  { id: 'e020', category: 'movie', emoji: '👻🍞', options: ['Ghost', 'Casper', 'Coco', 'The Sixth Sense'], correctIndex: 0 },
  { id: 'e021', category: 'phrase', emoji: '🐦🌍', options: ['It\'s a small world', 'Bird\'s eye view', 'Early bird', 'Free as a bird'], correctIndex: 2 },
  { id: 'e022', category: 'phrase', emoji: '🍰🎂🎉', options: ['Piece of cake', 'Happy birthday', 'Icing on the cake', 'Have your cake and eat it'], correctIndex: 0 },
  { id: 'e023', category: 'phrase', emoji: '🐝🎩', options: ['Bee in your bonnet', 'Mad hatter', 'Busy bee', 'Queen bee'], correctIndex: 0 },
  { id: 'e024', category: 'phrase', emoji: '🌧️🐱🐶', options: ["Raining cats and dogs", 'A dog\'s life', 'It never rains but it pours', 'Every cloud has a silver lining'], correctIndex: 0 },
  { id: 'e025', category: 'phrase', emoji: '🦵🍀', options: ['Break a leg', 'Lucky break', 'Leg up', 'Kick up your heels'], correctIndex: 0 },
  { id: 'e026', category: 'phrase', emoji: '🧊❄️🕶️', options: ['Cool as a cucumber', 'Ice cold', 'Chill out', 'Break the ice'], correctIndex: 0 },
  { id: 'e027', category: 'phrase', emoji: '🐘🏠', options: ['Elephant in the room', 'White elephant', 'An elephant never forgets', 'Herd mentality'], correctIndex: 0 },
  { id: 'e028', category: 'phrase', emoji: '⏰🐦', options: ['The early bird catches the worm', "Time flies", 'Clockwork', 'Watch the clock'], correctIndex: 0 },
  { id: 'e029', category: 'phrase', emoji: '🌟🤩', options: ['Star-struck', 'Shooting star', 'See stars', 'Reach for the stars'], correctIndex: 0 },
  { id: 'e030', category: 'phrase', emoji: '🍞🧈', options: ['Bread and butter', 'Best thing since sliced bread', 'Butter someone up', 'Know which side your bread is buttered'], correctIndex: 0 },
  { id: 'e031', category: 'food', emoji: '🍕', options: ['Pizza', 'Pasta', 'Bread', 'Cheese'], correctIndex: 0 },
  { id: 'e032', category: 'food', emoji: '🍔🍟', options: ['Burger and fries', 'Hot dog', 'Sandwich', 'Fish and chips'], correctIndex: 0 },
  { id: 'e033', category: 'food', emoji: '🍣🍚', options: ['Sushi', 'Rice pudding', 'Paella', 'Risotto'], correctIndex: 0 },
  { id: 'e034', category: 'food', emoji: '🌮🌶️', options: ['Taco', 'Burrito', 'Nachos', 'Fajita'], correctIndex: 0 },
  { id: 'e035', category: 'food', emoji: '🍝🍅', options: ['Spaghetti bolognese', 'Lasagne', 'Pizza', 'Risotto'], correctIndex: 0 },
  { id: 'e036', category: 'food', emoji: '🥞🍯', options: ['Pancakes with syrup', 'Waffles', 'French toast', 'Crepes'], correctIndex: 0 },
  { id: 'e037', category: 'food', emoji: '🍦🍫', options: ['Chocolate ice cream', 'Chocolate cake', 'Brownie', 'Hot chocolate'], correctIndex: 0 },
  { id: 'e038', category: 'food', emoji: '🥐☕', options: ['Croissant and coffee', 'Full English breakfast', 'Toast and tea', 'Bagel'], correctIndex: 0 },
  { id: 'e039', category: 'food', emoji: '🍗🍖', options: ['Roast dinner', 'BBQ', 'KFC', 'Sunday lunch'], correctIndex: 0 },
  { id: 'e040', category: 'food', emoji: '🍩', options: ['Doughnut', 'Bagel', 'Ring cake', 'Onion ring'], correctIndex: 0 },
  { id: 'e041', category: 'song', emoji: '☂️👑🎤', options: ['Umbrella - Rihanna', 'Purple Rain - Prince', 'Singing in the Rain', 'Diamonds - Rihanna'], correctIndex: 0 },
  { id: 'e042', category: 'song', emoji: '❄️👸🎵', options: ['Let It Go - Frozen', 'Ice Ice Baby', 'Cold Heart - Elton John', 'Winter Wonderland'], correctIndex: 0 },
  { id: 'e043', category: 'song', emoji: '💃🕺✨', options: ['Dancing Queen - ABBA', 'Uptown Funk', 'Dance Monkey', 'Footloose'], correctIndex: 1 },
  { id: 'e044', category: 'song', emoji: '🌈🎵', options: ['Somewhere Over the Rainbow', 'True Colors', 'Colors of the Wind', 'Rainbow - Kesha'], correctIndex: 0 },
  { id: 'e045', category: 'song', emoji: '👑🐝', options: ['Queen Bey (Beyoncé)', 'Killer Queen - Queen', 'Bohemian Rhapsody', 'Royals'], correctIndex: 0 },
  { id: 'e046', category: 'tv', emoji: '👑🏰📺', options: ['The Crown', 'Game of Thrones', 'Bridgerton', 'The Tudors'], correctIndex: 0 },
  { id: 'e047', category: 'tv', emoji: '🧟🚶', options: ['The Walking Dead', 'Z Nation', 'World War Z', 'iZombie'], correctIndex: 0 },
  { id: 'e048', category: 'tv', emoji: '🐉🔥👑', options: ['Game of Thrones', 'House of the Dragon', 'Merlin', 'The Hobbit'], correctIndex: 0 },
  { id: 'e049', category: 'tv', emoji: '🧪💰🚐', options: ['Breaking Bad', 'Ozark', 'Weeds', 'Narcos'], correctIndex: 0 },
  { id: 'e050', category: 'tv', emoji: '🏝️🌊✈️', options: ['Lost', 'Survivor', 'Love Island', 'Castaway'], correctIndex: 0 },
  { id: 'e051', category: 'general', emoji: '🌙🚶', options: ['Moonwalk', 'Sleepwalk', 'Astronaut', 'Werewolf'], correctIndex: 0 },
  { id: 'e052', category: 'general', emoji: '🐝🍯', options: ['Honey', 'Beeswax', 'Pollen', 'Nectar'], correctIndex: 0 },
  { id: 'e053', category: 'general', emoji: '🎃👻🍬', options: ['Halloween', 'Christmas', 'Easter', 'Bonfire Night'], correctIndex: 0 },
  { id: 'e054', category: 'general', emoji: '🎄🎁❄️', options: ['Christmas', 'New Year', 'Winter Solstice', 'Boxing Day'], correctIndex: 0 },
  { id: 'e055', category: 'general', emoji: '💐💍👰', options: ['Wedding', 'Engagement', 'Anniversary', 'Prom'], correctIndex: 0 },
  { id: 'e056', category: 'general', emoji: '🎓📜', options: ['Graduation', 'Diploma', 'Library', 'Exam'], correctIndex: 0 },
  { id: 'e057', category: 'general', emoji: '🏖️☀️🍹', options: ['Beach holiday', 'Summer', 'Cocktail hour', 'Pool party'], correctIndex: 0 },
  { id: 'e058', category: 'general', emoji: '🎬🍿', options: ['Movie night', 'Cinema', 'Premiere', 'Netflix and chill'], correctIndex: 0 },
  { id: 'e059', category: 'general', emoji: '🚀🌕', options: ['Moon landing', 'Space Race', 'Rocket launch', 'Astronaut'], correctIndex: 0 },
  { id: 'e060', category: 'general', emoji: '⚽🏆🌍', options: ['World Cup', 'Olympics', 'Champions League', 'Euros'], correctIndex: 0 },
  { id: 'e061', category: 'movie', emoji: '🐭🏰🎩', options: ['Cinderella', 'Sleeping Beauty', 'Aladdin', 'Snow White'], correctIndex: 0 },
  { id: 'e062', category: 'movie', emoji: '🍫🍫🐿️', options: ["Charlie and the Chocolate Factory", 'Ratatouille', 'Chicken Little', 'Alvin and the Chipmunks'], correctIndex: 0 },
  { id: 'e063', category: 'movie', emoji: '🧞‍♂️🪔', options: ['Aladdin', 'Genie', 'The Wizard of Oz', 'Arabian Nights'], correctIndex: 0 },
  { id: 'e064', category: 'movie', emoji: '🐝🍯🎬', options: ['Bee Movie', 'A Bug\'s Life', 'Antz', 'Minions'], correctIndex: 0 },
  { id: 'e065', category: 'movie', emoji: '👸🐸💋', options: ['The Princess and the Frog', 'Shrek', 'Frozen', 'Enchanted'], correctIndex: 0 },
  { id: 'e066', category: 'phrase', emoji: '🎣🐟', options: ['Something fishy', 'Reel it in', 'Plenty more fish in the sea', 'Fish out of water'], correctIndex: 2 },
  { id: 'e067', category: 'phrase', emoji: '🐷🩸', options: ['When pigs fly', 'Bring home the bacon', 'Pig out', 'Piggy bank'], correctIndex: 1 },
  { id: 'e068', category: 'phrase', emoji: '🌊🍵', options: ['A storm in a teacup', 'Sea change', 'Fish and chips', 'Rock the boat'], correctIndex: 0 },
  { id: 'e069', category: 'phrase', emoji: '🐴🔨', options: ['Beating a dead horse', 'Horsing around', 'Hold your horses', 'Straight from the horse\'s mouth'], correctIndex: 0 },
  { id: 'e070', category: 'phrase', emoji: '🎯🐝', options: ['Right on the money', 'Bullseye', 'Beeline', 'Sting like a bee'], correctIndex: 2 },
  { id: 'e071', category: 'food', emoji: '🥗🥑', options: ['Salad', 'Guacamole', 'Smoothie bowl', 'Avocado toast'], correctIndex: 0 },
  { id: 'e072', category: 'food', emoji: '🍜🍥', options: ['Ramen', 'Pho', 'Udon', 'Miso soup'], correctIndex: 0 },
  { id: 'e073', category: 'food', emoji: '🥧🎃', options: ['Pumpkin pie', 'Apple pie', 'Mince pie', 'Pecan pie'], correctIndex: 0 },
  { id: 'e074', category: 'food', emoji: '🧀🍷', options: ['Cheese and wine night', 'Fondue', 'Charcuterie board', 'Wine tasting'], correctIndex: 0 },
  { id: 'e075', category: 'food', emoji: '🍳🥓', options: ['Full English breakfast', 'Eggs benedict', 'Brunch', 'Omelette'], correctIndex: 0 },
  { id: 'e076', category: 'general', emoji: '💌❤️', options: ['Love letter', 'Valentine\'s Day', 'Pen pal', 'Heartfelt'], correctIndex: 0 },
  { id: 'e077', category: 'general', emoji: '🕯️🎂', options: ['Birthday', 'Candlelit dinner', 'Anniversary', 'Vigil'], correctIndex: 0 },
  { id: 'e078', category: 'general', emoji: '🌻🐝', options: ['Sunflower and bee', 'Springtime', 'Pollination', 'Garden'], correctIndex: 0 },
  { id: 'e079', category: 'general', emoji: '🏔️🥾', options: ['Hiking', 'Mountain climbing', 'Skiing', 'Camping'], correctIndex: 0 },
  { id: 'e080', category: 'general', emoji: '🐣🥚', options: ['Easter', 'Baby chick', 'Hatching', 'Springtime'], correctIndex: 0 },
];

module.exports = { EMOJI_PUZZLES };
