// Word Scramble Sprint word bank — single clean words (no spaces/punctuation)
// so letters can be shuffled and unshuffled unambiguously. Grows over time:
// append more entries with a unique id; nothing else needs to change.
const RAW = [
  'PIZZA', 'GUITAR', 'ELEPHANT', 'RAINBOW', 'CASTLE', 'DOLPHIN', 'VOLCANO', 'PENGUIN',
  'SANDWICH', 'UMBRELLA', 'BUTTERFLY', 'MOUNTAIN', 'CAMERA', 'PUZZLE', 'DESERT', 'JUNGLE',
  'ROCKET', 'PIRATE', 'DRAGON', 'WIZARD', 'ISLAND', 'GARDEN', 'BICYCLE', 'KITCHEN',
  'PILLOW', 'BLANKET', 'CANDLE', 'MIRROR', 'LADDER', 'WINDOW', 'FOREST', 'RIVER',
  'PLANET', 'GALAXY', 'COMET', 'METEOR', 'ASTRONAUT', 'TELESCOPE', 'COMPASS', 'TREASURE',
  'PIRATE', 'MERMAID', 'UNICORN', 'PHOENIX', 'GRIFFIN', 'CENTAUR', 'GOBLIN', 'FAIRY',
  'CHOCOLATE', 'PANCAKE', 'WAFFLE', 'COOKIE', 'CUPCAKE', 'DONUT', 'PRETZEL', 'POPCORN',
  'AVOCADO', 'BANANA', 'COCONUT', 'MANGO', 'PAPAYA', 'PINEAPPLE', 'STRAWBERRY', 'BLUEBERRY',
  'GUITAR', 'TRUMPET', 'VIOLIN', 'DRUMS', 'PIANO', 'FLUTE', 'HARMONICA', 'SAXOPHONE',
  'SOCCER', 'TENNIS', 'HOCKEY', 'BOWLING', 'BOXING', 'SURFING', 'SKIING', 'CYCLING',
  'DOCTOR', 'TEACHER', 'FARMER', 'PAINTER', 'SINGER', 'DANCER', 'WRITER', 'BAKER',
  'AIRPORT', 'STATION', 'HARBOR', 'BRIDGE', 'TUNNEL', 'HIGHWAY', 'VILLAGE', 'CANYON',
  'BLANKET', 'HAMMOCK', 'CAMPFIRE', 'LANTERN', 'BACKPACK', 'COMPASS', 'BINOCULARS', 'WHISTLE',
  'SPARKLE', 'GLITTER', 'CONFETTI', 'BALLOON', 'RIBBON', 'PRESENT', 'SURPRISE', 'CELEBRATE',
  'SUNSHINE', 'THUNDER', 'LIGHTNING', 'BLIZZARD', 'HURRICANE', 'TORNADO', 'DROUGHT', 'MONSOON',
  'KANGAROO', 'GIRAFFE', 'FLAMINGO', 'OCTOPUS', 'JELLYFISH', 'SEAHORSE', 'STARFISH', 'CRAB',
];

const SCRAMBLE_WORDS = Array.from(new Set(RAW)).map((word, i) => ({ id: i, word }));

module.exports = { SCRAMBLE_WORDS };
