// Trivia Showdown question bank — general-knowledge, objectively-correct
// questions across a spread of genres and 4 difficulty levels. `options` is
// always 4 choices, `correct` points at the right one (0-indexed). Grows
// over time: append more entries with a unique category/q pair; nothing
// else needs to change — ids, category and difficulty lists are all
// derived automatically at the bottom of this file.
//
// difficulty: 'easy' | 'medium' | 'hard' | 'expert'
const RAW = [
  // --- Geography ---------------------------------------------------------
  { category: 'geography', difficulty: 'easy', q: 'What is the capital of Australia?', options: ['Sydney', 'Melbourne', 'Canberra', 'Perth'], correct: 2 },
  { category: 'geography', difficulty: 'easy', q: 'Which is the largest ocean on Earth?', options: ['Atlantic', 'Indian', 'Arctic', 'Pacific'], correct: 3 },
  { category: 'geography', difficulty: 'easy', q: 'Mount Everest is located in which mountain range?', options: ['Andes', 'Himalayas', 'Alps', 'Rockies'], correct: 1 },
  { category: 'geography', difficulty: 'medium', q: 'Which country has the most natural lakes?', options: ['USA', 'Russia', 'Canada', 'Finland'], correct: 2 },
  { category: 'geography', difficulty: 'easy', q: 'What is the smallest country in the world?', options: ['Monaco', 'Vatican City', 'San Marino', 'Liechtenstein'], correct: 1 },
  { category: 'geography', difficulty: 'easy', q: 'The Sahara Desert is located on which continent?', options: ['Asia', 'Australia', 'Africa', 'South America'], correct: 2 },
  { category: 'geography', difficulty: 'medium', q: 'Which river is the longest in the world?', options: ['Amazon', 'Nile', 'Yangtze', 'Mississippi'], correct: 1 },
  { category: 'geography', difficulty: 'easy', q: 'What is the capital of Japan?', options: ['Osaka', 'Kyoto', 'Tokyo', 'Yokohama'], correct: 2 },
  { category: 'geography', difficulty: 'easy', q: 'Which country is shaped like a boot?', options: ['Spain', 'Greece', 'Italy', 'Portugal'], correct: 2 },
  { category: 'geography', difficulty: 'easy', q: 'The Great Barrier Reef is located off the coast of which country?', options: ['Thailand', 'Australia', 'Indonesia', 'Philippines'], correct: 1 },
  { category: 'geography', difficulty: 'easy', q: 'What is the capital of Canada?', options: ['Toronto', 'Vancouver', 'Ottawa', 'Montreal'], correct: 2 },
  { category: 'geography', difficulty: 'medium', q: 'Which is the smallest continent by land area?', options: ['Europe', 'Australia', 'Antarctica', 'South America'], correct: 1 },
  { category: 'geography', difficulty: 'medium', q: 'What is the longest mountain range in the world?', options: ['Rockies', 'Himalayas', 'Andes', 'Alps'], correct: 2 },
  { category: 'geography', difficulty: 'hard', q: 'Which African country was famously never colonized by a European power?', options: ['Kenya', 'Ethiopia', 'Nigeria', 'Sudan'], correct: 1 },
  { category: 'geography', difficulty: 'hard', q: 'What is the driest non-polar place on Earth?', options: ['Sahara Desert', 'Gobi Desert', 'Atacama Desert', 'Mojave Desert'], correct: 2 },
  { category: 'geography', difficulty: 'medium', q: 'Which two countries share the longest international land border?', options: ['USA and Mexico', 'Russia and China', 'Canada and USA', 'India and China'], correct: 2 },
  { category: 'geography', difficulty: 'easy', q: 'What is the capital of Egypt?', options: ['Alexandria', 'Cairo', 'Giza', 'Luxor'], correct: 1 },
  { category: 'geography', difficulty: 'medium', q: 'Mount Kilimanjaro is located in which country?', options: ['Kenya', 'Tanzania', 'Uganda', 'Ethiopia'], correct: 1 },
  { category: 'geography', difficulty: 'expert', q: 'Which strait separates Russia and Alaska?', options: ['Strait of Gibraltar', 'Bering Strait', 'Bass Strait', 'Cook Strait'], correct: 1 },
  { category: 'geography', difficulty: 'expert', q: 'What is the deepest known point in the ocean called?', options: ['Puerto Rico Trench', 'Java Trench', 'Challenger Deep', 'Tonga Trench'], correct: 2 },
  { category: 'geography', difficulty: 'expert', q: 'Which country has the most time zones, including its overseas territories?', options: ['Russia', 'USA', 'France', 'United Kingdom'], correct: 2 },
  { category: 'geography', difficulty: 'medium', q: 'Which South American country is named after the equator?', options: ['Colombia', 'Ecuador', 'Peru', 'Venezuela'], correct: 1 },

  // --- Science -------------------------------------------------------------
  { category: 'science', difficulty: 'easy', q: 'What is the chemical symbol for gold?', options: ['Ag', 'Au', 'Gd', 'Go'], correct: 1 },
  { category: 'science', difficulty: 'easy', q: 'How many bones are in the adult human body?', options: ['186', '206', '226', '246'], correct: 1 },
  { category: 'science', difficulty: 'easy', q: 'What planet is known as the Red Planet?', options: ['Venus', 'Jupiter', 'Mars', 'Saturn'], correct: 2 },
  { category: 'science', difficulty: 'easy', q: 'What gas do plants absorb from the atmosphere?', options: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'], correct: 2 },
  { category: 'science', difficulty: 'medium', q: 'What is the powerhouse of the cell?', options: ['Nucleus', 'Ribosome', 'Mitochondria', 'Golgi body'], correct: 2 },
  { category: 'science', difficulty: 'easy', q: 'What is the hardest natural substance on Earth?', options: ['Gold', 'Iron', 'Diamond', 'Quartz'], correct: 2 },
  { category: 'science', difficulty: 'easy', q: 'How many planets are in our solar system?', options: ['7', '8', '9', '10'], correct: 1 },
  { category: 'science', difficulty: 'easy', q: 'What force keeps us on the ground?', options: ['Magnetism', 'Friction', 'Gravity', 'Inertia'], correct: 2 },
  { category: 'science', difficulty: 'easy', q: 'What is the boiling point of water in Celsius?', options: ['90°C', '100°C', '110°C', '120°C'], correct: 1 },
  { category: 'science', difficulty: 'medium', q: 'Which blood type is the universal donor?', options: ['A', 'B', 'AB', 'O negative'], correct: 3 },
  { category: 'science', difficulty: 'medium', q: 'What is the chemical symbol for sodium?', options: ['So', 'Sd', 'Na', 'S'], correct: 2 },
  { category: 'science', difficulty: 'medium', q: "What is the most abundant gas in Earth's atmosphere?", options: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Argon'], correct: 1 },
  { category: 'science', difficulty: 'easy', q: 'Who developed the theory of general relativity?', options: ['Isaac Newton', 'Albert Einstein', 'Niels Bohr', 'Galileo Galilei'], correct: 1 },
  { category: 'science', difficulty: 'easy', q: 'What is the smallest structural and functional unit of life?', options: ['Atom', 'Cell', 'Molecule', 'Organ'], correct: 1 },
  { category: 'science', difficulty: 'medium', q: 'What is the pH value of a neutral solution?', options: ['0', '7', '10', '14'], correct: 1 },
  { category: 'science', difficulty: 'hard', q: 'What is the scientific study of fungi called?', options: ['Botany', 'Mycology', 'Entomology', 'Herpetology'], correct: 1 },
  { category: 'science', difficulty: 'easy', q: 'Which subatomic particle carries a negative electric charge?', options: ['Proton', 'Neutron', 'Electron', 'Photon'], correct: 2 },
  { category: 'science', difficulty: 'medium', q: 'What is the atomic number of hydrogen?', options: ['0', '1', '2', '8'], correct: 1 },
  { category: 'science', difficulty: 'easy', q: 'Which scientist formulated the laws of motion and universal gravitation?', options: ['Charles Darwin', 'Isaac Newton', 'Nikola Tesla', 'James Watt'], correct: 1 },
  { category: 'science', difficulty: 'hard', q: 'What is the process called where a substance changes directly from a solid to a gas?', options: ['Evaporation', 'Condensation', 'Sublimation', 'Deposition'], correct: 2 },
  { category: 'science', difficulty: 'medium', q: 'Which human organ produces insulin?', options: ['Liver', 'Pancreas', 'Kidney', 'Spleen'], correct: 1 },
  { category: 'science', difficulty: 'hard', q: 'What is the name for a rock formed from cooled volcanic lava or magma?', options: ['Sedimentary', 'Metamorphic', 'Igneous', 'Fossil'], correct: 2 },

  // --- History ---------------------------------------------------------------
  { category: 'history', difficulty: 'easy', q: 'In what year did World War II end?', options: ['1943', '1945', '1947', '1950'], correct: 1 },
  { category: 'history', difficulty: 'easy', q: 'Who was the first President of the United States?', options: ['Thomas Jefferson', 'John Adams', 'George Washington', 'Benjamin Franklin'], correct: 2 },
  { category: 'history', difficulty: 'easy', q: 'The Great Wall is located in which country?', options: ['Japan', 'China', 'Mongolia', 'Korea'], correct: 1 },
  { category: 'history', difficulty: 'easy', q: 'Who painted the Mona Lisa?', options: ['Michelangelo', 'Leonardo da Vinci', 'Raphael', 'Donatello'], correct: 1 },
  { category: 'history', difficulty: 'easy', q: 'Which ancient civilization built the pyramids of Giza?', options: ['Romans', 'Greeks', 'Egyptians', 'Mayans'], correct: 2 },
  { category: 'history', difficulty: 'easy', q: 'The Titanic sank in which year?', options: ['1905', '1912', '1918', '1923'], correct: 1 },
  { category: 'history', difficulty: 'medium', q: 'Who was known as the "Maid of Orléans"?', options: ['Marie Antoinette', 'Joan of Arc', 'Catherine the Great', 'Eleanor of Aquitaine'], correct: 1 },
  { category: 'history', difficulty: 'medium', q: 'The Berlin Wall fell in which year?', options: ['1987', '1989', '1991', '1993'], correct: 1 },
  { category: 'history', difficulty: 'medium', q: 'Who was the first Emperor of Rome?', options: ['Julius Caesar', 'Nero', 'Augustus', 'Constantine'], correct: 2 },
  { category: 'history', difficulty: 'medium', q: 'In which year did the French Revolution begin?', options: ['1776', '1789', '1799', '1804'], correct: 1 },
  { category: 'history', difficulty: 'easy', q: 'Which empire was ruled by Genghis Khan?', options: ['Ottoman Empire', 'Mongol Empire', 'Persian Empire', 'Roman Empire'], correct: 1 },
  { category: 'history', difficulty: 'easy', q: 'The Renaissance began in which country?', options: ['France', 'Italy', 'Spain', 'Germany'], correct: 1 },
  { category: 'history', difficulty: 'easy', q: 'Who was the British Prime Minister during most of World War II?', options: ['Neville Chamberlain', 'Winston Churchill', 'Clement Attlee', 'Anthony Eden'], correct: 1 },
  { category: 'history', difficulty: 'hard', q: 'In what year was the Berlin Wall built?', options: ['1955', '1961', '1968', '1975'], correct: 1 },
  { category: 'history', difficulty: 'medium', q: 'Which document did King John of England sign in 1215?', options: ['The Declaration of Rights', 'The Magna Carta', 'The Domesday Book', 'The Treaty of Windsor'], correct: 1 },
  { category: 'history', difficulty: 'easy', q: 'The Cold War was primarily a standoff between the United States and which country?', options: ['China', 'Soviet Union', 'North Korea', 'Cuba'], correct: 1 },
  { category: 'history', difficulty: 'easy', q: 'Who was the first person to walk on the Moon?', options: ['Buzz Aldrin', 'Yuri Gagarin', 'Neil Armstrong', 'John Glenn'], correct: 2 },
  { category: 'history', difficulty: 'easy', q: 'The American Civil War was fought between the Union and which side?', options: ['The Loyalists', 'The Confederacy', 'The Patriots', 'The Rebels of 1812'], correct: 1 },
  { category: 'history', difficulty: 'medium', q: 'Which Egyptian queen was famously allied with both Julius Caesar and Mark Antony?', options: ['Nefertiti', 'Cleopatra', 'Hatshepsut', 'Ankhesenamun'], correct: 1 },
  { category: 'history', difficulty: 'medium', q: 'The Industrial Revolution began in which country?', options: ['France', 'Germany', 'Great Britain', 'United States'], correct: 2 },
  { category: 'history', difficulty: 'easy', q: 'Which explorer is credited with reaching the Americas in 1492?', options: ['Ferdinand Magellan', 'Christopher Columbus', 'Vasco da Gama', 'Marco Polo'], correct: 1 },
  { category: 'history', difficulty: 'medium', q: 'What was the name of the ship that brought the Pilgrims to America in 1620?', options: ['The Santa Maria', 'The Mayflower', 'The Endeavour', 'The Beagle'], correct: 1 },
  { category: 'history', difficulty: 'hard', q: 'Which ancient wonder of the world was located in Alexandria, Egypt?', options: ['The Hanging Gardens', 'The Colossus of Rhodes', 'The Lighthouse of Alexandria', 'The Temple of Artemis'], correct: 2 },
  { category: 'history', difficulty: 'expert', q: 'Whose assassination in Sarajevo in 1914 is credited with triggering World War I?', options: ['Kaiser Wilhelm II', 'Archduke Franz Ferdinand', 'Tsar Nicholas II', 'King Alexander I'], correct: 1 },

  // --- Movies ----------------------------------------------------------------
  { category: 'movies', difficulty: 'easy', q: 'Who directed "Jurassic Park"?', options: ['George Lucas', 'Steven Spielberg', 'James Cameron', 'Ridley Scott'], correct: 1 },
  { category: 'movies', difficulty: 'medium', q: 'Which 1997 film won 11 Academy Awards including Best Picture?', options: ['Titanic', 'Braveheart', 'Forrest Gump', 'Gladiator'], correct: 0 },
  { category: 'movies', difficulty: 'easy', q: "In 'The Wizard of Oz', what color are Dorothy's slippers?", options: ['Blue', 'Silver', 'Ruby', 'Gold'], correct: 2 },
  { category: 'movies', difficulty: 'easy', q: 'Who played the Joker in "The Dark Knight" (2008)?', options: ['Jack Nicholson', 'Heath Ledger', 'Joaquin Phoenix', 'Jared Leto'], correct: 1 },
  { category: 'movies', difficulty: 'easy', q: 'Which animation studio produces the "Toy Story" films?', options: ['DreamWorks', 'Pixar', 'Illumination', 'Blue Sky Studios'], correct: 1 },
  { category: 'movies', difficulty: 'medium', q: 'Who directed "Pulp Fiction"?', options: ['Martin Scorsese', 'Quentin Tarantino', 'Guy Ritchie', 'David Fincher'], correct: 1 },
  { category: 'movies', difficulty: 'easy', q: "In 'Star Wars', who is Luke Skywalker's father?", options: ['Obi-Wan Kenobi', 'Yoda', 'Darth Vader', 'Emperor Palpatine'], correct: 2 },
  { category: 'movies', difficulty: 'easy', q: 'Which actor played Iron Man in the Marvel Cinematic Universe?', options: ['Chris Evans', 'Chris Hemsworth', 'Robert Downey Jr.', 'Mark Ruffalo'], correct: 2 },
  { category: 'movies', difficulty: 'easy', q: 'What is the name of the fictional boarding school in "Harry Potter"?', options: ['Beauxbatons', 'Durmstrang', 'Hogwarts', 'Ilvermorny'], correct: 2 },
  { category: 'movies', difficulty: 'medium', q: 'Who directed both "Inception" and "Interstellar"?', options: ['Denis Villeneuve', 'Christopher Nolan', 'James Cameron', 'Ridley Scott'], correct: 1 },
  { category: 'movies', difficulty: 'medium', q: 'Which 1994 film features a shrimp company called "Bubba Gump"?', options: ['Cast Away', 'Forrest Gump', 'Big', 'The Terminal'], correct: 1 },
  { category: 'movies', difficulty: 'easy', q: "In 'The Lion King', what is Simba's father's name?", options: ['Scar', 'Mufasa', 'Zazu', 'Rafiki'], correct: 1 },
  { category: 'movies', difficulty: 'expert', q: 'Which film won the first-ever Academy Award for Best Picture, in 1929?', options: ['Sunrise', 'Wings', 'Metropolis', 'The Jazz Singer'], correct: 1 },
  { category: 'movies', difficulty: 'hard', q: 'Who composed the film scores for "Jaws," "Star Wars," and "E.T."?', options: ['Hans Zimmer', 'John Williams', 'Danny Elfman', 'Alan Silvestri'], correct: 1 },
  { category: 'movies', difficulty: 'medium', q: "What is the name of Woody's owner in 'Toy Story'?", options: ['Sid', 'Andy', 'Buster', 'Wheezy'], correct: 1 },
  { category: 'movies', difficulty: 'easy', q: 'Which actress played Katniss Everdeen in "The Hunger Games"?', options: ['Emma Watson', 'Jennifer Lawrence', 'Kristen Stewart', 'Shailene Woodley'], correct: 1 },
  { category: 'movies', difficulty: 'medium', q: "In 'Back to the Future,' what type of car is the time machine?", options: ['Ford Mustang', 'DeLorean', 'Chevrolet Camaro', 'Volkswagen Beetle'], correct: 1 },
  { category: 'movies', difficulty: 'easy', q: 'Which animated film features the song "Let It Go"?', options: ['Moana', 'Tangled', 'Frozen', 'Encanto'], correct: 2 },
  { category: 'movies', difficulty: 'medium', q: 'Which film is famous for the line "I\'ll be back"?', options: ['RoboCop', 'The Terminator', 'Predator', 'Total Recall'], correct: 1 },
  { category: 'movies', difficulty: 'easy', q: "In 'The Lord of the Rings', what is the name of Elijah Wood's hobbit character?", options: ['Samwise Gamgee', 'Peregrin Took', 'Frodo Baggins', 'Meriadoc Brandybuck'], correct: 2 },

  // --- TV Shows ----------------------------------------------------------------
  { category: 'tv shows', difficulty: 'easy', q: "In 'Breaking Bad,' what is Walter White's drug-dealing alias?", options: ['Scarface', 'Heisenberg', 'El Jefe', 'The Cook'], correct: 1 },
  { category: 'tv shows', difficulty: 'easy', q: 'Which TV series is set in the fictional town of Hawkins, Indiana?', options: ['Riverdale', 'Stranger Things', 'The Umbrella Academy', 'Twin Peaks'], correct: 1 },
  { category: 'tv shows', difficulty: 'medium', q: '"Winter is Coming" is the words of which "Game of Thrones" house?', options: ['House Lannister', 'House Stark', 'House Targaryen', 'House Baratheon'], correct: 1 },
  { category: 'tv shows', difficulty: 'easy', q: 'Which sitcom features the character Sheldon Cooper?', options: ['Community', 'The Big Bang Theory', 'Parks and Recreation', 'Silicon Valley'], correct: 1 },
  { category: 'tv shows', difficulty: 'easy', q: 'In "The Office" (US), what product does Dunder Mifflin sell?', options: ['Paper', 'Electronics', 'Insurance', 'Furniture'], correct: 0 },
  { category: 'tv shows', difficulty: 'easy', q: 'Which animated show follows the Simpson family in Springfield?', options: ['Family Guy', 'The Simpsons', 'King of the Hill', 'Bob\'s Burgers'], correct: 1 },
  { category: 'tv shows', difficulty: 'hard', q: "What is the name of the hospital in 'Grey's Anatomy'?", options: ['Mercy West', 'St. Ambrose Hospital', 'Seattle Grace Hospital', 'Chicago Med'], correct: 2 },
  { category: 'tv shows', difficulty: 'medium', q: 'On what street does Sherlock Holmes live, in the address "221B"?', options: ['Downing Street', 'Baker Street', 'Fleet Street', 'Abbey Road'], correct: 1 },
  { category: 'tv shows', difficulty: 'medium', q: 'Which HBO series follows the Roy family and their media empire?', options: ['Billions', 'Succession', 'Empire', 'Dynasty'], correct: 1 },
  { category: 'tv shows', difficulty: 'easy', q: "What is the name of the Doctor's time-traveling ship in 'Doctor Who'?", options: ['The Nautilus', 'The TARDIS', 'The Enterprise', 'The Millennium Falcon'], correct: 1 },
  { category: 'tv shows', difficulty: 'medium', q: 'Which sitcom is set in the fictional Pawnee, Indiana, following a parks department?', options: ['Brooklyn Nine-Nine', 'Parks and Recreation', 'The Office', 'Superstore'], correct: 1 },
  { category: 'tv shows', difficulty: 'medium', q: 'What does "SVU" stand for in "Law & Order: SVU"?', options: ['Special Victims Unit', 'Serious Violations Unit', 'State Vice Unit', 'Special Verdict Unit'], correct: 0 },
  { category: 'tv shows', difficulty: 'easy', q: '"The Crown" is a drama primarily about which British monarch?', options: ['Queen Victoria', 'King George VI', 'Queen Elizabeth II', 'King Charles III'], correct: 2 },
  { category: 'tv shows', difficulty: 'hard', q: "What is the name of the fictional prison in 'Orange Is the New Black'?", options: ['Fox River', 'Litchfield Penitentiary', 'Oswald State', 'Shawshank'], correct: 1 },
  { category: 'tv shows', difficulty: 'hard', q: 'In the classic sitcom "M*A*S*H," what does the title stand for?', options: ['Medical Aid Surgical Hospital', 'Mobile Army Surgical Hospital', 'Military Advanced Surgical Hub', 'Mobile Aid Station Hospital'], correct: 1 },
  { category: 'tv shows', difficulty: 'expert', q: 'Which British sitcom is set in a Torquay hotel run by the irritable Basil?', options: ['Are You Being Served?', 'Fawlty Towers', "'Allo 'Allo!", 'Blackadder'], correct: 1 },
  { category: 'tv shows', difficulty: 'medium', q: "What is the name of the bar in 'How I Met Your Mother'?", options: ["Cheers", "MacLaren's Pub", "Paddy's Pub", "The Regal Beagle"], correct: 1 },

  // --- Music -----------------------------------------------------------------
  { category: 'music', difficulty: 'easy', q: 'Who is known as the "King of Pop"?', options: ['Elvis Presley', 'Prince', 'Michael Jackson', 'James Brown'], correct: 2 },
  { category: 'music', difficulty: 'easy', q: "Which band's members included John, Paul, George, and Ringo?", options: ['The Rolling Stones', 'The Beatles', 'The Who', 'Led Zeppelin'], correct: 1 },
  { category: 'music', difficulty: 'easy', q: 'Who sang "Bohemian Rhapsody"?', options: ['Queen', 'The Eagles', 'Fleetwood Mac', 'Journey'], correct: 0 },
  { category: 'music', difficulty: 'easy', q: 'Which artist released the album "1989"?', options: ['Katy Perry', 'Taylor Swift', 'Ariana Grande', 'Adele'], correct: 1 },
  { category: 'music', difficulty: 'easy', q: 'What instrument does a "cellist" play?', options: ['Violin', 'Cello', 'Viola', 'Double bass'], correct: 1 },
  { category: 'music', difficulty: 'medium', q: 'Who composed "The Four Seasons"?', options: ['Johann Sebastian Bach', 'Antonio Vivaldi', 'Wolfgang Amadeus Mozart', 'Franz Joseph Haydn'], correct: 1 },
  { category: 'music', difficulty: 'easy', q: 'Which girl group sang "Wannabe"?', options: ['Destiny\'s Child', 'Spice Girls', 'TLC', 'Girls Aloud'], correct: 1 },
  { category: 'music', difficulty: 'medium', q: 'Who is known as the "Queen of Soul"?', options: ['Diana Ross', 'Aretha Franklin', 'Whitney Houston', 'Tina Turner'], correct: 1 },
  { category: 'music', difficulty: 'medium', q: 'Which rapper released the album "The Marshall Mathers LP"?', options: ['Jay-Z', 'Eminem', 'Dr. Dre', '50 Cent'], correct: 1 },
  { category: 'music', difficulty: 'easy', q: 'What was the stage name of Stefani Germanotta?', options: ['Lady Gaga', 'Katy Perry', 'Rihanna', 'Pink'], correct: 0 },
  { category: 'music', difficulty: 'medium', q: 'Which composer continued composing after going deaf, including his famous Ninth Symphony?', options: ['Johannes Brahms', 'Ludwig van Beethoven', 'Franz Schubert', 'Frédéric Chopin'], correct: 1 },
  { category: 'music', difficulty: 'medium', q: 'Which band performed "Stairway to Heaven"?', options: ['Deep Purple', 'Led Zeppelin', 'Black Sabbath', 'Pink Floyd'], correct: 1 },
  { category: 'music', difficulty: 'hard', q: 'Which album is commonly cited as the best-selling album of all time?', options: ["Thriller", "Back in Black", "The Dark Side of the Moon", "Rumours"], correct: 0 },
  { category: 'music', difficulty: 'hard', q: 'Which major music festival is held annually at Worthy Farm in England?', options: ['Coachella', 'Glastonbury', 'Reading Festival', 'Isle of Wight Festival'], correct: 1 },
  { category: 'music', difficulty: 'medium', q: 'Who wrote the opera "The Magic Flute"?', options: ['Giuseppe Verdi', 'Wolfgang Amadeus Mozart', 'Richard Wagner', 'Giacomo Puccini'], correct: 1 },
  { category: 'music', difficulty: 'easy', q: 'Which instrument typically has 88 keys?', options: ['Organ', 'Accordion', 'Piano', 'Harpsichord'], correct: 2 },
  { category: 'music', difficulty: 'hard', q: 'What nationality was the composer Frédéric Chopin?', options: ['French', 'Polish', 'Austrian', 'Hungarian'], correct: 1 },
  { category: 'music', difficulty: 'medium', q: 'Which musical genre originated in Jamaica in the late 1960s?', options: ['Ska', 'Reggae', 'Calypso', 'Dancehall'], correct: 1 },
  { category: 'music', difficulty: 'medium', q: 'Kurt Cobain was the lead singer of which band?', options: ['Pearl Jam', 'Soundgarden', 'Nirvana', 'Alice in Chains'], correct: 2 },
  { category: 'music', difficulty: 'hard', q: 'What does the musical term "a cappella" mean?', options: ['Very fast tempo', 'Singing without instrumental accompaniment', 'Playing softly', 'A duet between two voices'], correct: 1 },
  { category: 'music', difficulty: 'medium', q: 'Which South American country is considered the birthplace of the tango?', options: ['Brazil', 'Chile', 'Argentina', 'Colombia'], correct: 2 },

  // --- Video Games -------------------------------------------------------------
  { category: 'video games', difficulty: 'easy', q: 'Which iconic video game franchise features a plumber named Mario?', options: ['Sonic the Hedgehog', 'Super Mario', 'Donkey Kong', 'Crash Bandicoot'], correct: 1 },
  { category: 'video games', difficulty: 'easy', q: 'Which company created the "PlayStation" console?', options: ['Microsoft', 'Nintendo', 'Sony', 'Sega'], correct: 2 },
  { category: 'video games', difficulty: 'easy', q: 'In "Minecraft," what is the most basic material used to make early tools?', options: ['Stone', 'Wood', 'Iron', 'Diamond'], correct: 1 },
  { category: 'video games', difficulty: 'medium', q: 'Which video game series features the supersoldier "Master Chief"?', options: ['Gears of War', 'Halo', 'Call of Duty', 'Destiny'], correct: 1 },
  { category: 'video games', difficulty: 'easy', q: 'What does "NPC" stand for in gaming?', options: ['New Player Character', 'Non-Player Character', 'Next Playable Character', 'Network Player Connection'], correct: 1 },
  { category: 'video games', difficulty: 'easy', q: 'Which company developed "The Legend of Zelda"?', options: ['Sega', 'Capcom', 'Nintendo', 'Square Enix'], correct: 2 },
  { category: 'video games', difficulty: 'easy', q: 'In "Among Us," what is the name of the traitor role?', options: ['Saboteur', 'Impostor', 'Betrayer', 'Infiltrator'], correct: 1 },
  { category: 'video games', difficulty: 'easy', q: 'Which battle royale game features 100 players dropping onto an island from a bus?', options: ['Apex Legends', 'PUBG', 'Fortnite', 'Warzone'], correct: 2 },
  { category: 'video games', difficulty: 'hard', q: 'What is the name of the silent protagonist in the "Half-Life" series?', options: ['Master Chief', 'Gordon Freeman', 'Doom Slayer', 'Isaac Clarke'], correct: 1 },
  { category: 'video games', difficulty: 'medium', q: 'Which game franchise includes "Skyrim" and "Oblivion"?', options: ['Fallout', 'The Witcher', 'The Elder Scrolls', 'Dragon Age'], correct: 2 },
  { category: 'video games', difficulty: 'easy', q: 'In "Pac-Man," what are the ghosts trying to do?', options: ['Escape the maze', 'Eat all the dots', 'Catch Pac-Man', 'Collect fruit'], correct: 2 },
  { category: 'video games', difficulty: 'hard', q: "Which console was Nintendo's direct successor to the Wii?", options: ['Wii U', 'GameCube', 'Nintendo Switch', 'Nintendo 3DS'], correct: 0 },
  { category: 'video games', difficulty: 'medium', q: 'Which sandbox game is the best-selling video game of all time?', options: ['Grand Theft Auto V', 'Minecraft', 'Tetris', 'Wii Sports'], correct: 1 },
  { category: 'video games', difficulty: 'medium', q: 'Which company created "Fortnite"?', options: ['Ubisoft', 'Epic Games', 'Activision', 'Valve'], correct: 1 },
  { category: 'video games', difficulty: 'easy', q: "In 'The Legend of Zelda' series, what is the name of the main protagonist?", options: ['Zelda', 'Link', 'Ganon', 'Epona'], correct: 1 },
  { category: 'video games', difficulty: 'expert', q: 'Which genre classification, abbreviated "MOBA," describes games like "League of Legends"?', options: ['Massively Online Battle Arcade', 'Multiplayer Online Battle Arena', 'Massive Objective-Based Adventure', 'Multiplayer Objective Battle Assault'], correct: 1 },
  { category: 'video games', difficulty: 'hard', q: 'What was the first commercially successful video game, released by Atari in 1972?', options: ['Space Invaders', 'Pong', 'Asteroids', 'Breakout'], correct: 1 },

  // --- Mythology -----------------------------------------------------------
  { category: 'mythology', difficulty: 'easy', q: 'In Greek mythology, who is the king of the gods?', options: ['Poseidon', 'Hades', 'Zeus', 'Apollo'], correct: 2 },
  { category: 'mythology', difficulty: 'easy', q: 'Who is the Norse god of thunder?', options: ['Odin', 'Loki', 'Thor', 'Baldr'], correct: 2 },
  { category: 'mythology', difficulty: 'medium', q: 'In Egyptian mythology, who is the god of the afterlife?', options: ['Ra', 'Anubis', 'Osiris', 'Horus'], correct: 2 },
  { category: 'mythology', difficulty: 'medium', q: 'What creature has the body of a lion and the head of a human, famous in Egyptian mythology?', options: ['Griffin', 'Sphinx', 'Chimera', 'Manticore'], correct: 1 },
  { category: 'mythology', difficulty: 'hard', q: 'In Greek mythology, who was condemned to push a boulder up a hill for eternity?', options: ['Tantalus', 'Prometheus', 'Sisyphus', 'Atlas'], correct: 2 },
  { category: 'mythology', difficulty: 'easy', q: 'Who is the Greek goddess of love and beauty?', options: ['Athena', 'Hera', 'Artemis', 'Aphrodite'], correct: 3 },
  { category: 'mythology', difficulty: 'expert', q: "What is the name of Odin's eight-legged horse in Norse mythology?", options: ['Svaðilfari', 'Sleipnir', 'Skinfaxi', 'Grani'], correct: 1 },
  { category: 'mythology', difficulty: 'medium', q: 'Who is the Roman equivalent of the Greek god Zeus?', options: ['Mars', 'Neptune', 'Jupiter', 'Apollo'], correct: 2 },
  { category: 'mythology', difficulty: 'easy', q: 'What is the name of the underworld in Greek mythology?', options: ['Hades', 'Tartarus', 'Elysium', 'Olympus'], correct: 0 },
  { category: 'mythology', difficulty: 'easy', q: 'In Greek mythology, who flew too close to the sun with wings of feathers and wax?', options: ['Daedalus', 'Icarus', 'Perseus', 'Theseus'], correct: 1 },
  { category: 'mythology', difficulty: 'medium', q: 'Who is the Egyptian sun god?', options: ['Ra', 'Thoth', 'Set', 'Geb'], correct: 0 },
  { category: 'mythology', difficulty: 'medium', q: 'In Norse mythology, what is the name for the event marking the end of the world?', options: ['Valhalla', 'Ragnarök', 'Yggdrasil', 'Niflheim'], correct: 1 },
  { category: 'mythology', difficulty: 'easy', q: 'Which Greek hero is famous for completing twelve labors?', options: ['Achilles', 'Heracles', 'Odysseus', 'Jason'], correct: 1 },
  { category: 'mythology', difficulty: 'medium', q: 'What is the name of the three-headed dog guarding the underworld in Greek mythology?', options: ['Fenrir', 'Cerberus', 'Orthrus', 'Ladon'], correct: 1 },
  { category: 'mythology', difficulty: 'medium', q: 'In Hindu mythology, who is the god of destruction, part of the Trimurti?', options: ['Vishnu', 'Brahma', 'Shiva', 'Indra'], correct: 2 },
  { category: 'mythology', difficulty: 'easy', q: 'Who is the trickster god in Norse mythology?', options: ['Loki', 'Heimdall', 'Tyr', 'Freyr'], correct: 0 },

  // --- Literature --------------------------------------------------------------
  { category: 'literature', difficulty: 'easy', q: 'Who wrote "Romeo and Juliet"?', options: ['Charles Dickens', 'William Shakespeare', 'Christopher Marlowe', 'Ben Jonson'], correct: 1 },
  { category: 'literature', difficulty: 'easy', q: 'Who wrote "Pride and Prejudice"?', options: ['Charlotte Brontë', 'Jane Austen', 'Emily Brontë', 'George Eliot'], correct: 1 },
  { category: 'literature', difficulty: 'hard', q: 'Which novel begins with the line "Call me Ishmael"?', options: ['Moby-Dick', 'The Old Man and the Sea', 'Treasure Island', '20,000 Leagues Under the Sea'], correct: 0 },
  { category: 'literature', difficulty: 'medium', q: 'Who wrote both "1984" and "Animal Farm"?', options: ['Aldous Huxley', 'George Orwell', 'Ray Bradbury', 'H.G. Wells'], correct: 1 },
  { category: 'literature', difficulty: 'easy', q: "What is the name of the young wizard in J.K. Rowling's book series?", options: ['Ron Weasley', 'Harry Potter', 'Neville Longbottom', 'Draco Malfoy'], correct: 1 },
  { category: 'literature', difficulty: 'medium', q: 'Who wrote "The Great Gatsby"?', options: ['Ernest Hemingway', 'F. Scott Fitzgerald', 'John Steinbeck', 'William Faulkner'], correct: 1 },
  { category: 'literature', difficulty: 'hard', q: 'Which Shakespeare play features the characters Rosencrantz and Guildenstern?', options: ['Macbeth', 'Hamlet', 'Othello', 'King Lear'], correct: 1 },
  { category: 'literature', difficulty: 'medium', q: 'Who wrote "To Kill a Mockingbird"?', options: ['Harper Lee', 'Toni Morrison', 'Flannery O\'Connor', 'Carson McCullers'], correct: 0 },
  { category: 'literature', difficulty: 'medium', q: "What is the first published book in C.S. Lewis's 'Chronicles of Narnia'?", options: ['Prince Caspian', 'The Lion, the Witch and the Wardrobe', 'The Magician\'s Nephew', 'The Silver Chair'], correct: 1 },
  { category: 'literature', difficulty: 'hard', q: 'Who wrote the epic novel "War and Peace"?', options: ['Fyodor Dostoevsky', 'Leo Tolstoy', 'Anton Chekhov', 'Ivan Turgenev'], correct: 1 },
  { category: 'literature', difficulty: 'easy', q: "In 'The Lord of the Rings,' what is the name of Frodo's home region?", options: ['Rohan', 'Gondor', 'The Shire', 'Mordor'], correct: 2 },
  { category: 'literature', difficulty: 'medium', q: 'Who created the detective character Sherlock Holmes?', options: ['Agatha Christie', 'Sir Arthur Conan Doyle', 'Wilkie Collins', 'G.K. Chesterton'], correct: 1 },
  { category: 'literature', difficulty: 'medium', q: 'Which author created the character Ebenezer Scrooge?', options: ['Charles Dickens', 'Thomas Hardy', 'Anthony Trollope', 'Wilkie Collins'], correct: 0 },
  { category: 'literature', difficulty: 'hard', q: 'Who wrote the dystopian novel "Brave New World"?', options: ['George Orwell', 'Aldous Huxley', 'Ray Bradbury', 'Kurt Vonnegut'], correct: 1 },
  { category: 'literature', difficulty: 'medium', q: "Which epic poem tells of Odysseus's long journey home after the Trojan War?", options: ['The Iliad', 'The Aeneid', 'The Odyssey', 'Metamorphoses'], correct: 2 },

  // --- Technology ----------------------------------------------------------
  { category: 'technology', difficulty: 'easy', q: 'Who co-founded Apple alongside Steve Wozniak?', options: ['Bill Gates', 'Steve Jobs', 'Elon Musk', 'Larry Page'], correct: 1 },
  { category: 'technology', difficulty: 'easy', q: 'What does "CPU" stand for?', options: ['Computer Processing Unit', 'Central Processing Unit', 'Core Program Utility', 'Central Program Unit'], correct: 1 },
  { category: 'technology', difficulty: 'easy', q: 'Which company owns and develops the Android operating system?', options: ['Apple', 'Microsoft', 'Google', 'Samsung'], correct: 2 },
  { category: 'technology', difficulty: 'medium', q: 'What does "HTML" stand for?', options: ['HyperText Markup Language', 'HighText Machine Language', 'HyperTransfer Markup Language', 'HyperText Machine Language'], correct: 0 },
  { category: 'technology', difficulty: 'easy', q: 'Who is credited as a co-founder of Microsoft?', options: ['Steve Jobs', 'Bill Gates', 'Jeff Bezos', 'Tim Cook'], correct: 1 },
  { category: 'technology', difficulty: 'medium', q: 'What does "URL" stand for?', options: ['Uniform Resource Locator', 'Universal Reference Link', 'Uniform Reference Locator', 'Universal Resource Link'], correct: 0 },
  { category: 'technology', difficulty: 'medium', q: 'Which social media platform was originally launched as "TheFacebook"?', options: ['MySpace', 'Facebook', 'Friendster', 'LinkedIn'], correct: 1 },
  { category: 'technology', difficulty: 'easy', q: 'What does "AI" commonly stand for in tech?', options: ['Automated Intelligence', 'Artificial Intelligence', 'Applied Informatics', 'Advanced Interface'], correct: 1 },
  { category: 'technology', difficulty: 'medium', q: 'Who is widely credited as the inventor of the World Wide Web?', options: ['Vint Cerf', 'Tim Berners-Lee', 'Marc Andreessen', 'Larry Page'], correct: 1 },
  { category: 'technology', difficulty: 'easy', q: 'What does "GPS" stand for?', options: ['Global Positioning System', 'Geographic Position Sensor', 'General Positioning Service', 'Global Pathing System'], correct: 0 },
  { category: 'technology', difficulty: 'expert', q: 'What was the name of the first widely-used graphical web browser, released in 1993?', options: ['Netscape Navigator', 'Mosaic', 'Internet Explorer', 'Lynx'], correct: 1 },
  { category: 'technology', difficulty: 'medium', q: 'What does "USB" stand for?', options: ['Universal Serial Bus', 'United System Bus', 'Universal System Board', 'Unified Serial Board'], correct: 0 },
  { category: 'technology', difficulty: 'easy', q: 'Which popular programming language shares its name with a type of snake?', options: ['Java', 'Ruby', 'Python', 'C++'], correct: 2 },
  { category: 'technology', difficulty: 'easy', q: 'Who founded Amazon?', options: ['Jack Ma', 'Jeff Bezos', 'Elon Musk', 'Larry Ellison'], correct: 1 },
  { category: 'technology', difficulty: 'medium', q: 'What does "RAM" stand for in computing?', options: ['Random Access Memory', 'Rapid Access Module', 'Read Access Memory', 'Random Application Memory'], correct: 0 },
  { category: 'technology', difficulty: 'easy', q: 'Which company created the iPhone?', options: ['Samsung', 'Google', 'Apple', 'Sony'], correct: 2 },

  // --- Sports -----------------------------------------------------------------
  { category: 'sports', difficulty: 'easy', q: 'How many players are on a standard football (soccer) team on the field?', options: ['9', '10', '11', '12'], correct: 2 },
  { category: 'sports', difficulty: 'easy', q: 'In which sport would you perform a slam dunk?', options: ['Volleyball', 'Basketball', 'Tennis', 'Baseball'], correct: 1 },
  { category: 'sports', difficulty: 'easy', q: 'How often are the Summer Olympic Games held?', options: ['Every 2 years', 'Every 3 years', 'Every 4 years', 'Every 5 years'], correct: 2 },
  { category: 'sports', difficulty: 'easy', q: 'What sport is known as "the beautiful game"?', options: ['Rugby', 'Cricket', 'Football (soccer)', 'Tennis'], correct: 2 },
  { category: 'sports', difficulty: 'medium', q: 'How many points is a touchdown worth in American football?', options: ['3', '6', '7', '8'], correct: 1 },
  { category: 'sports', difficulty: 'medium', q: 'In tennis, what is a score of zero called?', options: ['Love', 'Nil', 'Duck', 'Ace'], correct: 0 },
  { category: 'sports', difficulty: 'medium', q: 'Which country has won the most FIFA World Cups?', options: ['Germany', 'Argentina', 'Brazil', 'Italy'], correct: 2 },
  { category: 'sports', difficulty: 'easy', q: 'How many players from each team are on the court in basketball?', options: ['4', '5', '6', '7'], correct: 1 },
  { category: 'sports', difficulty: 'medium', q: 'In golf, what is the term for finishing a hole one stroke under par?', options: ['Bogey', 'Eagle', 'Birdie', 'Albatross'], correct: 2 },
  { category: 'sports', difficulty: 'easy', q: 'How many rings are on the Olympic flag?', options: ['4', '5', '6', '7'], correct: 1 },
  { category: 'sports', difficulty: 'hard', q: 'How many rounds are typically in a professional championship boxing match?', options: ['8', '10', '12', '15'], correct: 2 },
  { category: 'sports', difficulty: 'easy', q: 'Which sport uses the terms "love," "deuce," and "ace"?', options: ['Badminton', 'Tennis', 'Squash', 'Table tennis'], correct: 1 },
  { category: 'sports', difficulty: 'hard', q: 'What is the maximum possible score in a single game of ten-pin bowling?', options: ['200', '250', '300', '350'], correct: 2 },
  { category: 'sports', difficulty: 'medium', q: 'In cricket, how many players are on each team?', options: ['9', '10', '11', '12'], correct: 2 },
  { category: 'sports', difficulty: 'medium', q: 'Which country is credited with inventing the modern sport of rugby?', options: ['France', 'England', 'Wales', 'New Zealand'], correct: 1 },
  { category: 'sports', difficulty: 'easy', q: 'How many holes are played in a standard round of golf?', options: ['9', '16', '18', '20'], correct: 2 },
  { category: 'sports', difficulty: 'medium', q: 'Scoring three goals in a single game is commonly called what, in sports like football and hockey?', options: ['A treble', 'A hat-trick', 'A triple play', 'A grand slam'], correct: 1 },

  // --- Food & Drink --------------------------------------------------------
  { category: 'food & drink', difficulty: 'easy', q: 'What is the main ingredient in guacamole?', options: ['Tomato', 'Avocado', 'Lime', 'Onion'], correct: 1 },
  { category: 'food & drink', difficulty: 'easy', q: 'Which country is credited with inventing pizza as we know it?', options: ['France', 'Greece', 'Italy', 'Spain'], correct: 2 },
  { category: 'food & drink', difficulty: 'hard', q: 'What type of pastry is used to make a croissant?', options: ['Shortcrust', 'Puff', 'Filo', 'Laminated'], correct: 3 },
  { category: 'food & drink', difficulty: 'easy', q: 'Sushi originated in which country?', options: ['China', 'Japan', 'Korea', 'Thailand'], correct: 1 },
  { category: 'food & drink', difficulty: 'medium', q: 'What is the primary ingredient in traditional hummus?', options: ['Lentils', 'Chickpeas', 'Black beans', 'Peas'], correct: 1 },
  { category: 'food & drink', difficulty: 'medium', q: 'Which fruit has its seeds on the outside instead of the inside?', options: ['Kiwi', 'Fig', 'Strawberry', 'Passionfruit'], correct: 2 },
  { category: 'food & drink', difficulty: 'hard', q: 'What spice is derived from the crocus flower?', options: ['Turmeric', 'Saffron', 'Paprika', 'Cinnamon'], correct: 1 },
  { category: 'food & drink', difficulty: 'medium', q: 'Champagne must come from a specific region in which country?', options: ['Italy', 'Spain', 'France', 'Germany'], correct: 2 },
  { category: 'food & drink', difficulty: 'medium', q: 'What is traditional miso paste primarily made from?', options: ['Rice', 'Fermented soybeans', 'Wheat gluten', 'Lentils'], correct: 1 },
  { category: 'food & drink', difficulty: 'easy', q: 'What is tofu made from?', options: ['Chickpeas', 'Soybeans', 'Rice', 'Lentils'], correct: 1 },
  { category: 'food & drink', difficulty: 'medium', q: 'Which grain is fermented to produce Japanese sake?', options: ['Barley', 'Wheat', 'Rice', 'Corn'], correct: 2 },
  { category: 'food & drink', difficulty: 'medium', q: 'Which spice is derived from the bark of a tree?', options: ['Nutmeg', 'Cinnamon', 'Clove', 'Ginger'], correct: 1 },
  { category: 'food & drink', difficulty: 'medium', q: 'What is the base ingredient of traditional Greek tzatziki, alongside cucumber?', options: ['Sour cream', 'Yogurt', 'Cream cheese', 'Mayonnaise'], correct: 1 },
  { category: 'food & drink', difficulty: 'expert', q: "The croissant is said to have evolved from Austria's crescent-shaped pastry, the:", options: ['Strudel', 'Kipferl', 'Sachertorte', 'Linzer'], correct: 1 },
  { category: 'food & drink', difficulty: 'medium', q: 'Which country produces the most coffee in the world?', options: ['Colombia', 'Vietnam', 'Brazil', 'Ethiopia'], correct: 2 },
  { category: 'food & drink', difficulty: 'easy', q: 'What is the main ingredient in traditional Spanish paella?', options: ['Pasta', 'Rice', 'Potato', 'Couscous'], correct: 1 },
  { category: 'food & drink', difficulty: 'easy', q: 'Wine is made by fermenting which fruit?', options: ['Apples', 'Grapes', 'Berries', 'Plums'], correct: 1 },

  // --- Animals & Nature -----------------------------------------------------
  { category: 'animals & nature', difficulty: 'easy', q: 'What is the fastest land animal?', options: ['Lion', 'Cheetah', 'Gazelle', 'Horse'], correct: 1 },
  { category: 'animals & nature', difficulty: 'medium', q: 'How many hearts does an octopus have?', options: ['1', '2', '3', '4'], correct: 2 },
  { category: 'animals & nature', difficulty: 'medium', q: 'What is a group of lions called?', options: ['A pack', 'A pride', 'A herd', 'A colony'], correct: 1 },
  { category: 'animals & nature', difficulty: 'easy', q: 'Which bird is known for its ability to mimic human speech?', options: ['Eagle', 'Parrot', 'Owl', 'Falcon'], correct: 1 },
  { category: 'animals & nature', difficulty: 'easy', q: 'What is the largest mammal in the world?', options: ['African elephant', 'Blue whale', 'Giraffe', 'Polar bear'], correct: 1 },
  { category: 'animals & nature', difficulty: 'easy', q: 'How many legs does a spider have?', options: ['6', '8', '10', '12'], correct: 1 },
  { category: 'animals & nature', difficulty: 'easy', q: 'What do you call a baby kangaroo?', options: ['Cub', 'Joey', 'Kid', 'Pup'], correct: 1 },
  { category: 'animals & nature', difficulty: 'easy', q: 'Which animal is known to sleep for up to 20 hours a day?', options: ['Sloth', 'Koala', 'Panda', 'Cat'], correct: 1 },
  { category: 'animals & nature', difficulty: 'easy', q: 'What is a baby cow called?', options: ['Kid', 'Calf', 'Foal', 'Fawn'], correct: 1 },
  { category: 'animals & nature', difficulty: 'easy', q: 'How many legs does an insect have?', options: ['4', '6', '8', '10'], correct: 1 },
  { category: 'animals & nature', difficulty: 'medium', q: 'Which is the only mammal capable of true, sustained flight?', options: ['Flying squirrel', 'Bat', 'Sugar glider', 'Colugo'], correct: 1 },
  { category: 'animals & nature', difficulty: 'easy', q: 'Which flightless bird is the largest living bird species?', options: ['Emu', 'Ostrich', 'Kiwi', 'Penguin'], correct: 1 },
  { category: 'animals & nature', difficulty: 'medium', q: 'What is a group of crows called?', options: ['A flock', 'A murder', 'A gaggle', 'A parliament'], correct: 1 },
  { category: 'animals & nature', difficulty: 'hard', q: "Approximately how long is an elephant's pregnancy (gestation period)?", options: ['9 months', '14 months', '22 months', '30 months'], correct: 2 },
  { category: 'animals & nature', difficulty: 'hard', q: 'Which big cat is unable to roar, unlike lions and tigers?', options: ['Jaguar', 'Leopard', 'Cheetah', 'Cougar'], correct: 2 },
  { category: 'animals & nature', difficulty: 'easy', q: 'What is the tallest land animal in the world?', options: ['Elephant', 'Giraffe', 'Camel', 'Horse'], correct: 1 },
  { category: 'animals & nature', difficulty: 'easy', q: 'Which animal is famous for changing color using specialized skin cells?', options: ['Iguana', 'Chameleon', 'Gecko', 'Salamander'], correct: 1 },
  { category: 'animals & nature', difficulty: 'easy', q: 'What is a group of fish called?', options: ['A pod', 'A school', 'A pack', 'A troop'], correct: 1 },
  { category: 'animals & nature', difficulty: 'expert', q: 'Which venomous snake is the only one known to build a nest for its eggs?', options: ['Black Mamba', 'King Cobra', 'Rattlesnake', 'Green Mamba'], correct: 1 },

  // --- Pop Culture -----------------------------------------------------------
  { category: 'pop culture', difficulty: 'medium', q: 'What is the name of the fictional African country in "Black Panther"?', options: ['Zamunda', 'Wakanda', 'Genosha', 'Sokovia'], correct: 1 },
  { category: 'pop culture', difficulty: 'medium', q: 'Who wrote the "Harry Potter" series?', options: ['J.R.R. Tolkien', 'C.S. Lewis', 'J.K. Rowling', 'Roald Dahl'], correct: 2 },
  { category: 'pop culture', difficulty: 'medium', q: "In 'Friends', what is the name of Ross's pet monkey?", options: ['Marcel', 'Chandler', 'Gunther', 'Mike'], correct: 0 },
  { category: 'pop culture', difficulty: 'easy', q: 'Which streaming service produced "Stranger Things"?', options: ['Hulu', 'Amazon Prime', 'Netflix', 'Disney+'], correct: 2 },
  { category: 'pop culture', difficulty: 'easy', q: 'Who played Jack in the movie "Titanic"?', options: ['Brad Pitt', 'Leonardo DiCaprio', 'Matt Damon', 'Tom Cruise'], correct: 1 },
  { category: 'pop culture', difficulty: 'easy', q: "What is Batman's secret identity?", options: ['Tony Stark', 'Bruce Wayne', 'Clark Kent', 'Peter Parker'], correct: 1 },
  { category: 'pop culture', difficulty: 'medium', q: 'Which artist released the album "Thriller"?', options: ['Prince', 'Michael Jackson', 'Stevie Wonder', 'Lionel Richie'], correct: 1 },
  { category: 'pop culture', difficulty: 'easy', q: 'What is the name of the coffee shop in "Friends"?', options: ['Central Perk', 'The Grind', "Java Joe's", 'Common Grounds'], correct: 0 },
  { category: 'pop culture', difficulty: 'medium', q: 'What is the highest-grossing genre at the global box office, historically speaking?', options: ['Horror', 'Superhero/Action', 'Romantic Comedy', 'Documentary'], correct: 1 },
  { category: 'pop culture', difficulty: 'hard', q: 'Which social platform popularized the short-form "story" format later copied by Instagram and Facebook?', options: ['Twitter', 'Snapchat', 'TikTok', 'Vine'], correct: 1 },
  { category: 'pop culture', difficulty: 'easy', q: 'Which video-sharing app is known for short, looping dance and lip-sync videos, launched globally in 2018?', options: ['TikTok', 'Vine', 'Triller', 'Byte'], correct: 0 },
  { category: 'pop culture', difficulty: 'medium', q: 'What is the name of the fictional wizarding sport played on broomsticks in "Harry Potter"?', options: ['Quodpot', 'Gobstones', 'Quidditch', 'Wizard Chess'], correct: 2 },

  // --- General Knowledge -------------------------------------------------------
  { category: 'general', difficulty: 'medium', q: 'How many continents are there?', options: ['5', '6', '7', '8'], correct: 2 },
  { category: 'general', difficulty: 'easy', q: 'What is the currency of Japan?', options: ['Won', 'Yuan', 'Yen', 'Ringgit'], correct: 2 },
  { category: 'general', difficulty: 'easy', q: 'How many colors are in a rainbow?', options: ['5', '6', '7', '8'], correct: 2 },
  { category: 'general', difficulty: 'medium', q: 'What is the largest organ in the human body?', options: ['Liver', 'Heart', 'Skin', 'Lungs'], correct: 2 },
  { category: 'general', difficulty: 'easy', q: 'How many sides does a hexagon have?', options: ['5', '6', '7', '8'], correct: 1 },
  { category: 'general', difficulty: 'medium', q: 'What language has the most native speakers worldwide?', options: ['English', 'Spanish', 'Mandarin Chinese', 'Hindi'], correct: 2 },
  { category: 'general', difficulty: 'easy', q: 'What is the freezing point of water in Fahrenheit?', options: ['0°F', '32°F', '40°F', '100°F'], correct: 1 },
  { category: 'general', difficulty: 'easy', q: 'How many strings does a standard guitar have?', options: ['4', '5', '6', '7'], correct: 2 },
  { category: 'general', difficulty: 'easy', q: 'What does "www" stand for?', options: ['World Wide Web', 'World Web Wide', 'Wide World Web', 'Web World Wide'], correct: 0 },
  { category: 'general', difficulty: 'easy', q: 'Which planet is closest to the sun?', options: ['Venus', 'Earth', 'Mercury', 'Mars'], correct: 2 },
  { category: 'general', difficulty: 'medium', q: 'How many minutes are in a full day?', options: ['1240', '1440', '1640', '1840'], correct: 1 },
  { category: 'general', difficulty: 'easy', q: 'What is the chemical formula for water?', options: ['CO2', 'H2O', 'O2', 'NaCl'], correct: 1 },
  { category: 'general', difficulty: 'easy', q: 'How many letters are in the English alphabet?', options: ['24', '25', '26', '27'], correct: 2 },
  { category: 'general', difficulty: 'hard', q: 'What is the largest desert in the world, including polar deserts?', options: ['Sahara', 'Gobi', 'Antarctic', 'Arabian'], correct: 2 },
  { category: 'general', difficulty: 'easy', q: 'What is the largest planet in our solar system?', options: ['Saturn', 'Jupiter', 'Neptune', 'Uranus'], correct: 1 },
  { category: 'general', difficulty: 'easy', q: 'How many players are needed to play a game of chess?', options: ['1', '2', '3', '4'], correct: 1 },
  { category: 'general', difficulty: 'easy', q: 'What is the capital of the United Kingdom?', options: ['Manchester', 'London', 'Birmingham', 'Liverpool'], correct: 1 },
  { category: 'general', difficulty: 'easy', q: 'Which shape has exactly three sides?', options: ['Square', 'Triangle', 'Pentagon', 'Hexagon'], correct: 1 },
  { category: 'general', difficulty: 'medium', q: 'What is the primary language spoken in Brazil?', options: ['Spanish', 'Portuguese', 'French', 'Italian'], correct: 1 },
  { category: 'general', difficulty: 'easy', q: 'What sweet substance do bees produce?', options: ['Syrup', 'Honey', 'Nectar', 'Molasses'], correct: 1 },

  // --- Love & Relationships -----------------------------------------------------
  { category: 'love & relationships', difficulty: 'easy', q: 'What flower is traditionally associated with romance?', options: ['Tulip', 'Rose', 'Daisy', 'Sunflower'], correct: 1 },
  { category: 'love & relationships', difficulty: 'medium', q: 'Which anniversary is traditionally the "Golden" anniversary?', options: ['25th', '40th', '50th', '60th'], correct: 2 },
  { category: 'love & relationships', difficulty: 'hard', q: 'In which city is the "Ponte Milvio" love-lock bridge tradition famous?', options: ['Paris', 'Venice', 'Rome', 'Florence'], correct: 2 },
  { category: 'love & relationships', difficulty: 'medium', q: 'What is the traditional gift for a 1st wedding anniversary?', options: ['Paper', 'Wood', 'Cotton', 'Leather'], correct: 0 },
  { category: 'love & relationships', difficulty: 'easy', q: 'Which Shakespeare play features the star-crossed lovers Romeo and Juliet?', options: ['Hamlet', 'Romeo and Juliet', 'Macbeth', 'Othello'], correct: 1 },
  { category: 'love & relationships', difficulty: 'easy', q: 'What day is traditionally celebrated as the day of love?', options: ['February 14th', 'March 1st', 'June 1st', 'January 1st'], correct: 0 },
  { category: 'love & relationships', difficulty: 'medium', q: 'What is the traditional gift for a 25th wedding anniversary?', options: ['Gold', 'Silver', 'Pearl', 'Ruby'], correct: 1 },
  { category: 'love & relationships', difficulty: 'medium', q: 'Which anniversary is traditionally known as the "Diamond" anniversary?', options: ['40th', '50th', '60th', '70th'], correct: 2 },
  { category: 'love & relationships', difficulty: 'hard', q: 'What is the traditional gift material for a 10th wedding anniversary?', options: ['Tin', 'Bronze', 'Silk', 'Steel'], correct: 0 },
  { category: 'love & relationships', difficulty: 'medium', q: 'Which hormone, often nicknamed the "love hormone," is linked to bonding and affection?', options: ['Adrenaline', 'Oxytocin', 'Dopamine', 'Serotonin'], correct: 1 },
  { category: 'love & relationships', difficulty: 'hard', q: 'What does the French phrase "coup de foudre" describe?', options: ['A breakup', 'Love at first sight', 'A marriage proposal', 'An anniversary'], correct: 1 },
  { category: 'love & relationships', difficulty: 'medium', q: "Which Greek god, equivalent to Rome's Cupid, is associated with love and desire?", options: ['Ares', 'Eros', 'Hermes', 'Apollo'], correct: 1 },
  { category: 'love & relationships', difficulty: 'easy', q: 'In most Western traditions, which finger is a wedding ring worn on?', options: ['Index finger', 'Middle finger', 'Ring finger', 'Little finger'], correct: 2 },
  { category: 'love & relationships', difficulty: 'hard', q: 'What is the traditional gift for a 5th wedding anniversary?', options: ['Wood', 'Iron', 'Copper', 'China'], correct: 0 },
  { category: 'love & relationships', difficulty: 'easy', q: "In Roman mythology, whose arrows were said to make people fall in love?", options: ['Mars', 'Cupid', 'Bacchus', 'Neptune'], correct: 1 },
  { category: 'love & relationships', difficulty: 'easy', q: 'Which precious stone is traditionally most associated with engagement rings?', options: ['Sapphire', 'Emerald', 'Diamond', 'Ruby'], correct: 2 },
];

const TRIVIA_QUESTIONS = RAW.map((q, i) => ({
  id: i,
  category: q.category,
  difficulty: q.difficulty,
  question: q.q,
  options: q.options,
  correctIndex: q.correct,
}));

const TRIVIA_CATEGORIES = [...new Set(TRIVIA_QUESTIONS.map((q) => q.category))].sort();
const TRIVIA_DIFFICULTIES = ['easy', 'medium', 'hard', 'expert'];

module.exports = { TRIVIA_QUESTIONS, TRIVIA_CATEGORIES, TRIVIA_DIFFICULTIES };
