// Trivia Showdown question bank — general-knowledge, objectively-correct
// questions across a spread of categories. `options` is always 4 choices,
// `correctIndex` points at the right one. Grows over time: append more
// entries with a unique id; nothing else needs to change.
const RAW = [
  { category: 'geography', q: 'What is the capital of Australia?', options: ['Sydney', 'Melbourne', 'Canberra', 'Perth'], correct: 2 },
  { category: 'geography', q: 'Which is the largest ocean on Earth?', options: ['Atlantic', 'Indian', 'Arctic', 'Pacific'], correct: 3 },
  { category: 'geography', q: 'Mount Everest is located in which mountain range?', options: ['Andes', 'Himalayas', 'Alps', 'Rockies'], correct: 1 },
  { category: 'geography', q: 'Which country has the most natural lakes?', options: ['USA', 'Russia', 'Canada', 'Finland'], correct: 2 },
  { category: 'geography', q: 'What is the smallest country in the world?', options: ['Monaco', 'Vatican City', 'San Marino', 'Liechtenstein'], correct: 1 },
  { category: 'geography', q: 'The Sahara Desert is located on which continent?', options: ['Asia', 'Australia', 'Africa', 'South America'], correct: 2 },
  { category: 'geography', q: 'Which river is the longest in the world?', options: ['Amazon', 'Nile', 'Yangtze', 'Mississippi'], correct: 1 },
  { category: 'geography', q: 'What is the capital of Japan?', options: ['Osaka', 'Kyoto', 'Tokyo', 'Yokohama'], correct: 2 },
  { category: 'geography', q: 'Which country is shaped like a boot?', options: ['Spain', 'Greece', 'Italy', 'Portugal'], correct: 2 },
  { category: 'geography', q: 'The Great Barrier Reef is located off the coast of which country?', options: ['Thailand', 'Australia', 'Indonesia', 'Philippines'], correct: 1 },

  { category: 'science', q: 'What is the chemical symbol for gold?', options: ['Ag', 'Au', 'Gd', 'Go'], correct: 1 },
  { category: 'science', q: 'How many bones are in the adult human body?', options: ['186', '206', '226', '246'], correct: 1 },
  { category: 'science', q: 'What planet is known as the Red Planet?', options: ['Venus', 'Jupiter', 'Mars', 'Saturn'], correct: 2 },
  { category: 'science', q: 'What gas do plants absorb from the atmosphere?', options: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'], correct: 2 },
  { category: 'science', q: 'What is the powerhouse of the cell?', options: ['Nucleus', 'Ribosome', 'Mitochondria', 'Golgi body'], correct: 2 },
  { category: 'science', q: 'What is the hardest natural substance on Earth?', options: ['Gold', 'Iron', 'Diamond', 'Quartz'], correct: 2 },
  { category: 'science', q: 'How many planets are in our solar system?', options: ['7', '8', '9', '10'], correct: 1 },
  { category: 'science', q: 'What force keeps us on the ground?', options: ['Magnetism', 'Friction', 'Gravity', 'Inertia'], correct: 2 },
  { category: 'science', q: 'What is the boiling point of water in Celsius?', options: ['90°C', '100°C', '110°C', '120°C'], correct: 1 },
  { category: 'science', q: 'Which blood type is the universal donor?', options: ['A', 'B', 'AB', 'O negative'], correct: 3 },

  { category: 'history', q: 'In what year did World War II end?', options: ['1943', '1945', '1947', '1950'], correct: 1 },
  { category: 'history', q: 'Who was the first President of the United States?', options: ['Thomas Jefferson', 'John Adams', 'George Washington', 'Benjamin Franklin'], correct: 2 },
  { category: 'history', q: 'The Great Wall is located in which country?', options: ['Japan', 'China', 'Mongolia', 'Korea'], correct: 1 },
  { category: 'history', q: 'Who painted the Mona Lisa?', options: ['Michelangelo', 'Leonardo da Vinci', 'Raphael', 'Donatello'], correct: 1 },
  { category: 'history', q: 'Which ancient civilization built the pyramids of Giza?', options: ['Romans', 'Greeks', 'Egyptians', 'Mayans'], correct: 2 },
  { category: 'history', q: 'The Titanic sank in which year?', options: ['1905', '1912', '1918', '1923'], correct: 1 },
  { category: 'history', q: 'Who was known as the "Maid of Orléans"?', options: ['Marie Antoinette', 'Joan of Arc', 'Catherine the Great', 'Eleanor of Aquitaine'], correct: 1 },
  { category: 'history', q: 'The Berlin Wall fell in which year?', options: ['1987', '1989', '1991', '1993'], correct: 1 },

  { category: 'pop culture', q: 'Who directed the movie "Jaws"?', options: ['George Lucas', 'Steven Spielberg', 'Martin Scorsese', 'James Cameron'], correct: 1 },
  { category: 'pop culture', q: 'Which band released the album "Abbey Road"?', options: ['The Rolling Stones', 'The Beatles', 'Led Zeppelin', 'Pink Floyd'], correct: 1 },
  { category: 'pop culture', q: 'What is the name of the fictional African country in "Black Panther"?', options: ['Zamunda', 'Wakanda', 'Genosha', 'Sokovia'], correct: 1 },
  { category: 'pop culture', q: 'Who wrote the "Harry Potter" series?', options: ['J.R.R. Tolkien', 'C.S. Lewis', 'J.K. Rowling', 'Roald Dahl'], correct: 2 },
  { category: 'pop culture', q: 'In "Friends", what is the name of Ross\'s pet monkey?', options: ['Marcel', 'Chandler', 'Gunther', 'Mike'], correct: 0 },
  { category: 'pop culture', q: 'Which streaming service produced "Stranger Things"?', options: ['Hulu', 'Amazon Prime', 'Netflix', 'Disney+'], correct: 2 },
  { category: 'pop culture', q: 'Who played Jack in the movie "Titanic"?', options: ['Brad Pitt', 'Leonardo DiCaprio', 'Matt Damon', 'Tom Cruise'], correct: 1 },
  { category: 'pop culture', q: 'What is Batman\'s secret identity?', options: ['Tony Stark', 'Bruce Wayne', 'Clark Kent', 'Peter Parker'], correct: 1 },
  { category: 'pop culture', q: 'Which artist released the album "Thriller"?', options: ['Prince', 'Michael Jackson', 'Stevie Wonder', 'Lionel Richie'], correct: 1 },
  { category: 'pop culture', q: 'What is the name of the coffee shop in "Friends"?', options: ['Central Perk', 'The Grind', 'Java Joe\'s', 'Common Grounds'], correct: 0 },

  { category: 'sports', q: 'How many players are on a standard football (soccer) team on the field?', options: ['9', '10', '11', '12'], correct: 2 },
  { category: 'sports', q: 'In which sport would you perform a slam dunk?', options: ['Volleyball', 'Basketball', 'Tennis', 'Baseball'], correct: 1 },
  { category: 'sports', q: 'How often are the Summer Olympic Games held?', options: ['Every 2 years', 'Every 3 years', 'Every 4 years', 'Every 5 years'], correct: 2 },
  { category: 'sports', q: 'What sport is known as "the beautiful game"?', options: ['Rugby', 'Cricket', 'Football (soccer)', 'Tennis'], correct: 2 },
  { category: 'sports', q: 'How many points is a touchdown worth in American football?', options: ['3', '6', '7', '8'], correct: 1 },
  { category: 'sports', q: 'In tennis, what is a score of zero called?', options: ['Love', 'Nil', 'Duck', 'Ace'], correct: 0 },
  { category: 'sports', q: 'Which country has won the most FIFA World Cups?', options: ['Germany', 'Argentina', 'Brazil', 'Italy'], correct: 2 },

  { category: 'food', q: 'What is the main ingredient in guacamole?', options: ['Tomato', 'Avocado', 'Lime', 'Onion'], correct: 1 },
  { category: 'food', q: 'Which country is credited with inventing pizza as we know it?', options: ['France', 'Greece', 'Italy', 'Spain'], correct: 2 },
  { category: 'food', q: 'What type of pastry is used to make a croissant?', options: ['Shortcrust', 'Puff', 'Filo', 'Laminated'], correct: 3 },
  { category: 'food', q: 'Sushi originated in which country?', options: ['China', 'Japan', 'Korea', 'Thailand'], correct: 1 },
  { category: 'food', q: 'What is the primary ingredient in traditional hummus?', options: ['Lentils', 'Chickpeas', 'Black beans', 'Peas'], correct: 1 },
  { category: 'food', q: 'Which fruit has seeds on the outside instead of the inside?', options: ['Kiwi', 'Fig', 'Strawberry', 'Passionfruit'], correct: 2 },
  { category: 'food', q: 'What spice is derived from the crocus flower?', options: ['Turmeric', 'Saffron', 'Paprika', 'Cinnamon'], correct: 1 },
  { category: 'food', q: 'Champagne must come from a specific region in which country?', options: ['Italy', 'Spain', 'France', 'Germany'], correct: 2 },

  { category: 'animals', q: 'What is the fastest land animal?', options: ['Lion', 'Cheetah', 'Gazelle', 'Horse'], correct: 1 },
  { category: 'animals', q: 'How many hearts does an octopus have?', options: ['1', '2', '3', '4'], correct: 2 },
  { category: 'animals', q: 'What is a group of lions called?', options: ['A pack', 'A pride', 'A herd', 'A colony'], correct: 1 },
  { category: 'animals', q: 'Which bird is known for its ability to mimic human speech?', options: ['Eagle', 'Parrot', 'Owl', 'Falcon'], correct: 1 },
  { category: 'animals', q: 'What is the largest mammal in the world?', options: ['African elephant', 'Blue whale', 'Giraffe', 'Polar bear'], correct: 1 },
  { category: 'animals', q: 'How many legs does a spider have?', options: ['6', '8', '10', '12'], correct: 1 },
  { category: 'animals', q: 'What do you call a baby kangaroo?', options: ['Cub', 'Joey', 'Kid', 'Pup'], correct: 1 },
  { category: 'animals', q: 'Which animal is known to sleep for up to 20 hours a day?', options: ['Sloth', 'Koala', 'Panda', 'Cat'], correct: 1 },

  { category: 'general', q: 'How many continents are there?', options: ['5', '6', '7', '8'], correct: 2 },
  { category: 'general', q: 'What is the currency of Japan?', options: ['Won', 'Yuan', 'Yen', 'Ringgit'], correct: 2 },
  { category: 'general', q: 'How many colors are in a rainbow?', options: ['5', '6', '7', '8'], correct: 2 },
  { category: 'general', q: 'What is the largest organ in the human body?', options: ['Liver', 'Heart', 'Skin', 'Lungs'], correct: 2 },
  { category: 'general', q: 'How many sides does a hexagon have?', options: ['5', '6', '7', '8'], correct: 1 },
  { category: 'general', q: 'What language has the most native speakers worldwide?', options: ['English', 'Spanish', 'Mandarin Chinese', 'Hindi'], correct: 2 },
  { category: 'general', q: 'What is the freezing point of water in Fahrenheit?', options: ['0°F', '32°F', '40°F', '100°F'], correct: 1 },
  { category: 'general', q: 'How many strings does a standard guitar have?', options: ['4', '5', '6', '7'], correct: 2 },
  { category: 'general', q: 'What is the tallest building in the world (as of the 2020s)?', options: ['Shanghai Tower', 'Burj Khalifa', 'One World Trade Center', 'Petronas Towers'], correct: 1 },
  { category: 'general', q: 'What does "www" stand for?', options: ['World Wide Web', 'World Web Wide', 'Wide World Web', 'Web World Wide'], correct: 0 },
  { category: 'general', q: 'Which planet is closest to the sun?', options: ['Venus', 'Earth', 'Mercury', 'Mars'], correct: 2 },
  { category: 'general', q: 'How many minutes are in a full day?', options: ['1240', '1440', '1640', '1840'], correct: 1 },
  { category: 'general', q: 'What is the chemical formula for water?', options: ['CO2', 'H2O', 'O2', 'NaCl'], correct: 1 },
  { category: 'general', q: 'How many letters are in the English alphabet?', options: ['24', '25', '26', '27'], correct: 2 },
  { category: 'general', q: 'What is the largest desert in the world (including polar deserts)?', options: ['Sahara', 'Gobi', 'Antarctic', 'Arabian'], correct: 2 },

  { category: 'love & relationships', q: 'What flower is traditionally associated with romance?', options: ['Tulip', 'Rose', 'Daisy', 'Sunflower'], correct: 1 },
  { category: 'love & relationships', q: 'Which anniversary is traditionally the "Golden" anniversary?', options: ['25th', '40th', '50th', '60th'], correct: 2 },
  { category: 'love & relationships', q: 'In which city is the "Ponte Milvio" love-lock bridge tradition famous?', options: ['Paris', 'Venice', 'Rome', 'Florence'], correct: 2 },
  { category: 'love & relationships', q: 'What is the traditional gift for a 1st wedding anniversary?', options: ['Paper', 'Wood', 'Cotton', 'Leather'], correct: 0 },
  { category: 'love & relationships', q: 'Which Shakespeare play features the star-crossed lovers Romeo and Juliet?', options: ['Hamlet', 'Romeo and Juliet', 'Macbeth', 'Othello'], correct: 1 },
  { category: 'love & relationships', q: 'What day is traditionally celebrated as the day of love?', options: ['February 14th', 'March 1st', 'June 1st', 'January 1st'], correct: 0 },
];

const TRIVIA_QUESTIONS = RAW.map((q, i) => ({
  id: i,
  category: q.category,
  question: q.q,
  options: q.options,
  correctIndex: q.correct,
}));

module.exports = { TRIVIA_QUESTIONS };
